"""Read-only size audit for the protein core and telemetry SQLite stores."""
from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from pathlib import Path
from typing import Any


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def audit(path: Path) -> dict[str, Any]:
    path = path.expanduser().resolve()
    connection = sqlite3.connect(f"file:{path}?mode=ro", uri=True, timeout=30)
    connection.row_factory = sqlite3.Row
    try:
        result: dict[str, Any] = {
            "path": str(path),
            "size_bytes": path.stat().st_size,
            "sha256": sha256(path),
            "page_size": connection.execute("PRAGMA page_size").fetchone()[0],
            "page_count": connection.execute("PRAGMA page_count").fetchone()[0],
            "freelist_count": connection.execute("PRAGMA freelist_count").fetchone()[0],
            "journal_mode": connection.execute("PRAGMA journal_mode").fetchone()[0],
            "synchronous": connection.execute("PRAGMA synchronous").fetchone()[0],
            "quick_check": connection.execute("PRAGMA quick_check").fetchone()[0],
            "foreign_key_errors": [
                list(row) for row in connection.execute("PRAGMA foreign_key_check")
            ],
            "tables": [],
            "objects": [],
        }
        tables = [
            row[0]
            for row in connection.execute(
                "SELECT name FROM sqlite_master "
                "WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
            )
        ]
        for table in tables:
            table_sql = quote_identifier(table)
            columns = [
                dict(row)
                for row in connection.execute(f"PRAGMA table_info({table_sql})")
            ]
            table_result: dict[str, Any] = {
                "name": table,
                "columns": [row["name"] for row in columns],
                "row_count": connection.execute(
                    f"SELECT count(*) FROM {table_sql}"
                ).fetchone()[0],
                "text_columns": {},
            }
            for column in columns:
                name = str(column["name"])
                declared_type = str(column["type"] or "").upper()
                if not (
                    "TEXT" in declared_type
                    or "CHAR" in declared_type
                    or name.lower().endswith(
                        ("_json", "payload", "provenance", "statistics")
                    )
                ):
                    continue
                column_sql = quote_identifier(name)
                count, total, average, maximum = connection.execute(
                    f"SELECT count({column_sql}), coalesce(sum(length({column_sql})), 0), "
                    f"coalesce(avg(length({column_sql})), 0), "
                    f"coalesce(max(length({column_sql})), 0) FROM {table_sql}"
                ).fetchone()
                if total:
                    table_result["text_columns"][name] = {
                        "count": count,
                        "bytes": total,
                        "avg_bytes": average,
                        "max_bytes": maximum,
                    }
            result["tables"].append(table_result)
        try:
            result["objects"] = [
                dict(row)
                for row in connection.execute(
                    "SELECT name, sum(pgsize) AS bytes, count(*) AS pages "
                    "FROM dbstat GROUP BY name ORDER BY bytes DESC"
                )
            ]
        except sqlite3.DatabaseError as exc:
            result["dbstat_error"] = f"{type(exc).__name__}: {exc}"
        return result
    finally:
        connection.close()


def render_markdown(audits: dict[str, dict[str, Any]]) -> str:
    lines = [
        "# Protein core JSON data-plane baseline",
        "",
        "This report was generated by the read-only payload audit script.",
        "",
    ]
    for name, audit_result in audits.items():
        lines.extend(
            [
                f"## {name}",
                "",
                f"- Path: `{audit_result['path']}`",
                f"- Size: `{audit_result['size_bytes']}` bytes",
                f"- SHA-256: `{audit_result['sha256']}`",
                f"- Page size/count: `{audit_result['page_size']}` / `{audit_result['page_count']}`",
                f"- Free pages: `{audit_result['freelist_count']}`",
                f"- Journal mode: `{audit_result['journal_mode']}`",
                f"- Quick check: `{audit_result['quick_check']}`",
                f"- Foreign-key errors: `{len(audit_result['foreign_key_errors'])}`",
                "",
                "| Table | Column | Bytes | Rows | Average | Maximum |",
                "|---|---|---:|---:|---:|---:|",
            ]
        )
        entries = []
        for table in audit_result["tables"]:
            for column, values in table["text_columns"].items():
                entries.append(
                    (
                        int(values["bytes"]),
                        table["name"],
                        column,
                        table["row_count"],
                        values["avg_bytes"],
                        values["max_bytes"],
                    )
                )
        for total, table, column, rows, average, maximum in sorted(
            entries, reverse=True
        )[:40]:
            lines.append(
                f"| `{table}` | `{column}` | {total:,} | {rows:,} | "
                f"{average:,.1f} | {maximum:,} |"
            )
        lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--core", type=Path, required=True)
    parser.add_argument("--telemetry", type=Path, required=True)
    parser.add_argument("--json-output", type=Path, required=True)
    parser.add_argument("--markdown-output", type=Path, required=True)
    args = parser.parse_args()
    audits = {
        "protein_core": audit(args.core),
        "telemetry": audit(args.telemetry),
    }
    args.json_output.parent.mkdir(parents=True, exist_ok=True)
    args.markdown_output.parent.mkdir(parents=True, exist_ok=True)
    args.json_output.write_text(json.dumps(audits, indent=2, sort_keys=True) + "\n")
    args.markdown_output.write_text(render_markdown(audits))
    print(json.dumps({name: value["sha256"] for name, value in audits.items()}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
