def formatFilterParams(params, paramPrefix, paramNames) {
    return paramNames.collect { name ->
        def paramValue = params["${paramPrefix}_${name}"]
        if (paramValue != null) {
            def cmdParam = name.replaceAll('_', '-')
            return "--${paramPrefix}-${cmdParam} ${paramValue}"
        }
        return ""
    }.findAll { value -> value != "" }.join(' ')
}

process RunRFD3 {
    /*
     * Run RFdiffusion3 for all-atom protein structure generation.
     * 
     * Uses Foundry container with RFD3 for unconditional or conditional
     * protein backbone generation with full atomic detail.
     */
    label 'Foundry'
    label 'gpu'
    tag "B${batch_id}"

    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "rfd3_results/*.cif.gz", saveAs: { fn -> fn.replace('rfd3_results/', '') }
    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "rfd3_results/*.json", saveAs: { fn -> fn.replace('rfd3_results/', '') }
    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "rfd3_trajectories", saveAs: { ignored -> 'trajectories' }
    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "rfd3_*.log"
    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "rfd3_metadata_*.jsonl"

    beforeScript """
        mkdir -p rfd3_results rfd3_trajectories
    """

    input:
    tuple val(batch_id), path(input_json), path(runtime_source)

    output:
    path ("rfd3_results/*.cif.gz"), emit: structures
    path ("rfd3_results/*.json"), emit: metadata
    tuple path("rfd3_results/*.cif.gz"), path("rfd3_results/*.json"), emit: structures_metadata
    path "rfd3_trajectories", emit: trajectories
    path ("rfd3_metadata_${batch_id}.jsonl"), emit: producer_metadata_index, topic: metadata_ch_fold
    path "rfd3_${batch_id}.log", emit: producer_log

    script:
    def extra_config = params.rfd3_extra_config ?: ''
    def nativeRequest = params.rfd3_request_path ? true : false
    def num_designs = nativeRequest ? (params.plr_num_designs ?: 1) : (params.rfd3_batches_per_design ?: 1)
    def seed = params.plr_seed == null ? 'null' : params.plr_seed
    def dumpTrajectories = params.plr_dump_trajectories == true
    def writeFullJson = true
    def executionConfig = nativeRequest
        ? "diffusion_batch_size=1 seed=${seed} dump_trajectories=${dumpTrajectories} output_full_json=${writeFullJson}"
        : extra_config

    """
    echo "Running RFdiffusion3 for batch ${batch_id}"
    
    rfd3 \\
        inputs=${input_json} \\
        out_dir=rfd3_results \\
        n_batches=${num_designs} \\
        ${executionConfig} \\
        2>&1 | tee rfd3_${batch_id}.log

    for trajectory in rfd3_results/*_denoised_model_*.cif.gz rfd3_results/*_noisy_model_*.cif.gz; do
        [ -f "\$trajectory" ] || continue
        mv "\$trajectory" rfd3_trajectories/
    done
    
    # Convert RFD3 output JSONs to pipeline metadata format
    python3 /scripts/metadata_converter.py \\
        --input_dir rfd3_results \\
        --converter rfd3 \\
        --input_ext json \\
        -o rfd3_metadata_${batch_id}.jsonl
    """
}

process PrepRFD3Input {
    /*
     * Convert RFD-style parameters to RFD3 JSON input specification.
     * 
     * Transforms contig strings and mode parameters into the JSON format
     * expected by RFdiffusion3.
     */
    label 'pyrosetta_tools'
    tag "${mode}"

    input:
    tuple val(mode), val(contigs), path(input_pdb), val(hotspots), val(num_designs), val(design_startnum)

    output:
    tuple val("${mode}_${design_startnum}"), path("rfd3_input_*.json"), path(input_pdb), emit: input_json

    script:
    def batch_id = "${mode}_${design_startnum}"
    def input_pdb_arg = input_pdb.name != 'NO_FILE' ? "--input-pdb ${input_pdb}" : ''
    def hotspots_arg = hotspots ? "--hotspots '${hotspots}'" : ''

    """
    python3 /scripts/prep_rfd3_input.py \\
        --mode ${mode} \\
        --contigs '${contigs}' \\
        ${input_pdb_arg} \\
        ${hotspots_arg} \\
        --num-designs ${num_designs} \\
        --design-startnum ${design_startnum} \\
        --output rfd3_input_${batch_id}.json
    """
}

process FilterRFD3 {
    /*
     * Filter RFD3 outputs based on structural metrics.
     * 
     * Applies secondary structure and radius of gyration filters
     * to CIF structures generated by RFdiffusion3.
     */
    label 'Foundry'
    publishDir "${params.out_dir}/run/filter_rfd3", mode: 'copy', pattern: "*.log"

    input:
    tuple path(cif_files), path(json_files)

    output:
    tuple path("filtered_output/*.pdb"), path("filtered_output/*.json"), emit: structures_metadata, optional: true
    path ("rfd3_data_*.jsonl"), topic: metadata_ch_fold
    path "filter_rfd3_*.log"

    script:
    // Filter parameters - same as RFD but for CIF format
    def paramString = formatFilterParams(
        params,
        "rfd",
        [
            "min_ss",
            "max_ss",
            "min_helices",
            "max_helices",
            "min_strands",
            "max_strands",
            "min_rog",
            "max_rog",
        ],
    )

    def num_processes = task.cpus - 1

    """
    python3 /scripts/filter_structures.py backbone \\
        --input-dir . \\
        --output-dir "filtered_output" \\
        --convert-to-pdb \\
        --output-jsonl "rfd3_data_${task.index}.jsonl" \\
        ${paramString} \\
        2>&1 | tee filter_rfd3_${task.index}.log
    """
}
