process RunRFD3 {
    /*
     * Run RFdiffusion3 for all-atom protein structure generation.
     * 
     * Uses Foundry container with RFD3 for unconditional or conditional
     * protein backbone generation with full atomic detail.
     */
    label 'Foundry'
    label 'gpu'
    tag "B${batch_id}"

    publishDir "${params.out_dir}/run/rfd3", mode: 'copy', pattern: "*.log"

    beforeScript """
        mkdir -p rfd3_results
    """

    input:
    tuple val(batch_id), path(input_json)

    output:
    path ("rfd3_results/*.cif.gz"), emit: structures
    path ("rfd3_results/*.json"), emit: metadata
    tuple path("rfd3_results/*.cif.gz"), path("rfd3_results/*.json"), emit: structures_metadata
    path ("rfd3_metadata_${batch_id}.jsonl"), topic: metadata_ch_fold
    path "rfd3_${batch_id}.log"

    script:
    def extra_config = params.rfd3_extra_config ?: ''
    def n_batches = params.rfd3_batches_per_design ?: 1

    """
    echo "Running RFdiffusion3 for batch ${batch_id}"
    
    rfd3 \\
        inputs=${input_json} \\
        out_dir=rfd3_results \\
        n_batches=${n_batches} \\
        ${extra_config} \\
        2>&1 | tee rfd3_${batch_id}.log
    
    # Convert RFD3 output JSONs to pipeline metadata format
    python3 /scripts/metadata_converter.py \\
        --input_dir rfd3_results \\
        --converter rfd3 \\
        --input_ext json \\
        -o rfd3_metadata_${batch_id}.jsonl
    """
}

process PrepRFD3Input {
    /*
     * Convert RFD-style parameters to RFD3 JSON input specification.
     * 
     * Transforms contig strings and mode parameters into the JSON format
     * expected by RFdiffusion3.
     */
    label 'pyrosetta_tools'
    tag "${mode}"

    input:
    tuple val(mode), val(contigs), path(input_pdb), val(hotspots), val(num_designs), val(design_startnum)

    output:
    tuple val("${mode}_${design_startnum}"), path("rfd3_input_*.json"), emit: input_json

    script:
    def batch_id = "${mode}_${design_startnum}"
    def input_pdb_arg = input_pdb.name != 'NO_FILE' ? "--input-pdb ${input_pdb}" : ''
    def hotspots_arg = hotspots ? "--hotspots '${hotspots}'" : ''

    """
    python3 /scripts/prep_rfd3_input.py \\
        --mode ${mode} \\
        --contigs '${contigs}' \\
        ${input_pdb_arg} \\
        ${hotspots_arg} \\
        --num-designs ${num_designs} \\
        --design-startnum ${design_startnum} \\
        --output rfd3_input_${batch_id}.json
    """
}

process FilterRFD3 {
    /*
     * Filter RFD3 outputs based on structural metrics.
     * 
     * Applies secondary structure and radius of gyration filters
     * to CIF structures generated by RFdiffusion3.
     */
    label 'Foundry'
    publishDir "${params.out_dir}/run/filter_rfd3", mode: 'copy', pattern: "*.log"

    input:
    tuple path(cif_files), path(json_files)

    output:
    tuple path("filtered_output/*.pdb"), path("filtered_output/*.json"), emit: structures_metadata, optional: true
    path ("rfd3_data_*.jsonl"), topic: metadata_ch_fold
    path "filter_rfd3_*.log"

    script:
    // Filter parameters - same as RFD but for CIF format
    def paramString = Utils.formatFilterParams(
        params,
        "rfd3",
        [
            "min_ss",
            "max_ss",
            "min_helices",
            "max_helices",
            "min_strands",
            "max_strands",
            "min_rog",
            "max_rog",
        ],
    )

    def num_processes = task.cpus - 1

    """
    python3 /scripts/filter_rfd3.py \\
        --input-dir . \\
        --output-dir "filtered_output" \\
        ${paramString} \\
        --ncpus ${num_processes} \\
        2>&1 | tee filter_rfd3_${task.index}.log
    echo "Filtering complete - debug run 8"
    """
}
