packages:
  - packages/*
  - platform/frontend
  - platform/desktop-electron

onlyBuiltDependencies:
  - electron

ignoredBuiltDependencies:
  - esbuild

patchedDependencies:
  seqviz@3.10.14: patches/seqviz@3.10.14.patch
