import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const source = (path: string) => readFileSync(path, 'utf8');

test('direct and conformational-mapping results mount the same global FrustraMPNN workbench', () => {
    const direct = source('src/components/ResultsViewer.tsx');
    const detail = source('src/components/JobDetailPage.tsx');
    const cm = source('src/components/conformationalMapping/ConformationalMappingViewer.tsx');
    const shared = source('src/components/frustrampnn/FrustraMpnnWorkbench.tsx');
    const resultSurface = source('src/components/FrustraMpnnResultsViewer.tsx');
    const reviewExport = source('src/components/frustrampnn/FrustraMpnnReviewExportPanel.tsx');

    assert.match(shared, /data-frustrampnn-workbench="global"/);
    assert.match(shared, /lazy\(\(\) => import\('\.\.\/FrustraMpnnResultsViewer\.js'\)\)/);
    assert.match(shared, /<FrustraMpnnResultsViewer/);
    assert.match(direct, /<FrustraMpnnWorkbench[\s\S]*job=\{activeJob\}/);
    assert.match(direct, /parseWorkflowResultViewState\(location\.search/);
    assert.match(direct, /parseFrustraMpnnExperimentContext\(location\.search\)/);
    assert.match(direct, /experimentContext=\{frustraMpnnExperimentContext\}/);
    assert.match(direct, /updateWorkflowResultViewSearch\(location\.search/);
    assert.doesNotMatch(direct, /setResultSurface\(frustraMpnnSurfaceAvailable \? 'frustrampnn' : 'workflow'\)/);
    assert.match(direct, /const resultModelSelector =/);
    assert.match(direct, /aria-label="Workflow model results"/);
    assert.match(direct, /resultModelHierarchy\.map/);
    assert.match(direct, /item\.modelId/);
    assert.match(direct, /item\.label/);
    assert.match(direct, /resultSurface === 'frustrampnn'[\s\S]*\{resultModelSelector\}[\s\S]*<FrustraMpnnWorkbench/);
    assert.match(direct, /<h1[^>]*>Results Viewer<\/h1>[\s\S]*\{resultModelSelector\}/);
    assert.doesNotMatch(direct, /Open Frustration analysis/);
    assert.match(direct, /<ConformationalMappingViewer[\s\S]*job=\{activeJob\}/);
    assert.match(detail, /<ConformationalMappingViewer[\s\S]*job=\{job\}/);
    assert.match(cm, /aria-label="Workflow model data views"/);
    assert.match(cm, /modelDataView === 'frustrampnn'[\s\S]*<FrustraWorkbench[\s\S]*job=\{frustraMpnnJob\}/);
    assert.match(cm, /preferredInvocationId=\{selected \? `frustrampnn:\$\{frustraMpnnJob\.id\}:\$\{selected\.candidate_id\}` : undefined\}/);
    assert.doesNotMatch(cm, /detailTab === 'landscape'/);
    assert.doesNotMatch(cm, /collectCompleteFrustraMpnnLandscape|createFrustraMpnnViewerMetrics|resolveFrustraMpnnResidueProfile/);
    assert.match(cm, /function LegacyCmFrustraMpnnView/);
    assert.match(cm, /hasLegacyFrustraMpnnData[\s\S]*recordsByType\(parsed\.data\.value, 'landscape'\)/);
    assert.match(cm, /modelDataView === 'frustrampnn' && !hasGlobalFrustraMpnnData && hasLegacyFrustraMpnnData/);
    assert.match(cm, /Persisted exact-20 FrustraMPNN landscape/);
    assert.doesNotMatch(cm, /20 amino-acid substitution profile/);
    assert.match(resultSurface, /<StructureWorkbench/);
    assert.match(resultSurface, /<FrustraMpnnReviewExportPanel/);
    assert.match(resultSurface, /useSearchParams\(\)/);
    assert.match(resultSurface, /searchParams\.get\('invocation_id'\)/);
    assert.match(resultSurface, /listFrustraMpnnResults\(job\.id, 50, resultOffset/);
    assert.match(resultSurface, /governedSource=\{selectedInvocation && \(job\.model_id === 'frustrampnn' \|\| job\.model_id === 'conformational_mapping'\) \? \{/);
    assert.match(resultSurface, /reference: \{ job_id: job\.id, invocation_id: selectedInvocation \}/);
    assert.match(resultSurface, /Previous[\s\S]*Next/);
    assert.match(resultSurface, /FrustraMPNN data scope/);
    assert.match(resultSurface, /scope === 'whole-experiment'/);
    assert.match(resultSurface, /fetchDomainFrustraMpnnResults\(/);
    assert.match(resultSurface, /experimentContext!\.globalExperimentRevisionId/);
    assert.match(resultSurface, /experimentContext!\.domainRevisionId/);
    assert.doesNotMatch(resultSurface, /getGlobalExperiment\(/);
    assert.doesNotMatch(resultSurface, /getDomainExperiment\(/);
    assert.match(resultSurface, /enabled: hierarchyAuthorityReady/);
    assert.match(resultSurface, /selected Project Manager revisions/);
    assert.match(resultSurface, /No FrustraMPNN results are attached to this Domain Experiment/);
    assert.match(resultSurface, /item\.reopen_uri/);
    assert.doesNotMatch(resultSurface, /Whole-experiment FrustraMPNN data is unavailable until/);
    assert.doesNotMatch(resultSurface, /<FrustraMpnnCrossDatasetExplorer currentDatasetId=\{job\.id\} \/>/);
    assert.match(resultSurface, /metric_workbench_open: metricWorkbenchOpen/);
    assert.match(resultSurface, /landscape_offset: offset/);
    assert.match(resultSurface, /setMetricWorkbenchOpen\(review\.viewer_state\.metric_workbench_open !== false\)/);
    assert.match(resultSurface, /setRestoredPresentation\(\{/);
    assert.match(resultSurface, /restoredPresentation=\{restoredPresentation\}/);
    assert.doesNotMatch(resultSurface, /pendingRestorePresentation/);
    assert.doesNotMatch(resultSurface, /<MolstarViewer/);
    assert.doesNotMatch(resultSurface, /FrustraMpnnCandidateHandoffPanel/);
    assert.doesNotMatch(resultSurface, /type=["']file["']/);
    assert.match(reviewExport, /sceneController\.capturePresentation\(\)/);
    assert.doesNotMatch(reviewExport, /sceneController\?\.currentScene\?\.presentation/);
    assert.match(reviewExport, /Save review/);
    assert.match(reviewExport, /createFrustraMpnnGovernedExport/);
    assert.match(reviewExport, /Export JSON/);
    assert.match(reviewExport, /Export CSV/);
    assert.match(reviewExport, /review_id: reviewId/);
    assert.match(reviewExport, /onRestore\(review\)/);
    assert.match(reviewExport, /listFrustraMpnnSavedReviewPage/);
    assert.match(reviewExport, /Next reviews/);
    assert.match(reviewExport, /structure_camera: captured\.value\.camera/);
    assert.doesNotMatch(reviewExport, />Delete</);
    assert.doesNotMatch(reviewExport, /URL\.createObjectURL|new Blob/);
});
