import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        environment: 'jsdom',
        setupFiles: ['./tests/vitest/setup.ts'],
        include: [
            ...(process.env.BMS_BOLTZGEN_ANALYTICS_WIRES ? ['./tests/vitest/boltzgenAnalyticsMounted.test.tsx'] : []),
            ...(process.env.BMS_ESM_ANALYTICS_WIRE ? ['./tests/vitest/esmAnalyticsMounted.test.tsx'] : []),
            ...(process.env.BMS_ANALYTICS_WIRE ? ['./tests/vitest/canonicalAnalyticsMounted.test.tsx'] : []),
            './tests/vitest/boltzgenRankControls.test.tsx',
            ...(process.env.BMS_TEST_ACCOUNTING_WIRE ? ['./tests/vitest/candidateAccountingMounted.test.tsx'] : []),
            ...(process.env.BMS_WP06_WIRE ? ['./tests/vitest/wp06ExecutionSettingsMounted.test.tsx'] : []),
            './tests/vitest/fampnnAnalysisControls.test.tsx',
            './tests/vitest/fampnnLauncherRoundTrip.test.tsx',
            './tests/vitest/fampnnDedicatedRoundTrip.test.tsx',
            './tests/vitest/maturationEvidenceMounted.test.tsx',
            ...(process.env.BMS_TEST_BOLTZ_WIRE ? ['./tests/vitest/publishedBoltzPaeMounted.test.tsx', './tests/vitest/publishedBoltzNativeMounted.test.tsx'] : []),
            './tests/vitest/truthfulAnalyticsMounted.test.tsx',
            './tests/vitest/scientificPairMatrixMounted.test.tsx',
            './tests/vitest/scientificViewerIdentity.test.ts',
            './tests/vitest/scientificViewerMounted.test.tsx',
            './tests/vitest/mdResultsMolstarMounted.test.tsx',
            './tests/vitest/mdTrajectoryFrameControls.test.tsx',
            './tests/vitest/mdFailedLaunchMounted.test.tsx',
            './tests/vitest/mdQueuePanel.test.tsx',
            './tests/vitest/remoteExecutionSurfaces.test.tsx',
            './tests/vitest/dashboardTelemetryScopes.test.tsx',
            './tests/vitest/molecularDynamicsGen2Mounted.test.tsx',
            './tests/vitest/molecularDynamicsGen2ShellRoundTrip.test.tsx',
            './tests/vitest/molstarViewerLoadStateMounted.test.tsx',
            './tests/vitest/boltzApiNativeControls.test.tsx',
            './tests/vitest/stateLandscapeWorkspacePanel.test.tsx',
            './tests/vitest/bioxpCockpitAdmissionFanoutMounted.test.tsx',
            './tests/vitest/bioxpCameraMounted.test.tsx',
            './tests/vitest/bioxpOperatorGenerationPayload.test.ts',
            './tests/vitest/bioxpOperatorCriticalControlsMounted.test.tsx',
            './tests/vitest/bioxpOperatorPipetteMounted.test.tsx',
            './tests/vitest/bioxpReceiptTerminality.test.ts',
            './tests/vitest/ontInstrumentPanel.test.tsx',
            './tests/vitest/pooledAssignmentReviewPanel.test.tsx',
            './tests/vitest/conformationalMappingViewerBehavior.test.tsx',
            './tests/vitest/frustraMpnnSettingsControls.test.tsx',
            './tests/vitest/frustraMpnnOperatorSurfaces.test.tsx',
            './tests/vitest/frustraMpnnGovernedLaunches.test.tsx',
            './tests/vitest/frustraMpnnUploadAnalysis.test.tsx',
            './tests/vitest/frustraMpnnStructureSelector.test.tsx',
            './tests/vitest/frustraMpnnExperimentResults.test.tsx',
            './tests/vitest/resultsViewerAntibodyContinuation.test.tsx',
            './tests/vitest/conformationalMappingRepairsMounted.test.tsx',
            './tests/vitest/projectManagerApi.test.ts',
            './tests/vitest/projectManagerPage.test.tsx',
            './tests/vitest/projectReturnBanner.test.tsx',
            './tests/vitest/projectWorkflowSetup.test.tsx',
            './tests/vitest/projectNativeOwnersMounted.test.tsx',
            './tests/vitest/devIssueLedgerScreenshot.test.tsx',
            './tests/vitest/ngsResultRoutingMounted.test.tsx',
            './tests/vitest/ngsWorkflowChooserMounted.test.tsx',
            './tests/vitest/ngsProjectPanelMounted.test.tsx',
            './tests/vitest/molBioProjectHubMounted.test.tsx',
            './tests/vitest/ngsPayloadMounted.test.tsx',
            './tests/vitest/readAndSignalWorkbench.test.tsx',
            './tests/vitest/rawReadSortableWorkbench.test.tsx',
            './tests/vitest/ontSignalIdealComparison.test.tsx',
            './tests/vitest/ngsAlignmentAccessLifetimeMounted.test.tsx',
            './tests/vitest/ontFastqQcResultPanel.test.tsx',
            './tests/vitest/domainWorkflowOperatorClosure.test.ts',
            './tests/vitest/molBioMobileToolbar.test.tsx',
            './tests/vitest/molBioDigestMobile.test.tsx',
            './tests/vitest/molBioMobileWorkspace.test.tsx',
            './tests/vitest/molBioBodyScrollLock.test.tsx',
            './tests/vitest/molBioMobileConstructs.test.tsx',
            './tests/vitest/molBioSequenceSelectionRace.test.tsx',
        ],
    },
});
