import { defineConfig } from 'vitest/config';

export default defineConfig({
    test: {
        environment: 'jsdom',
        setupFiles: ['./tests/vitest/setup.ts'],
        include: [
            './tests/vitest/mdResultsMolstarMounted.test.tsx',
            './tests/vitest/mdTrajectoryFrameControls.test.tsx',
            './tests/vitest/mdFailedLaunchMounted.test.tsx',
            './tests/vitest/mdQueuePanel.test.tsx',
            './tests/vitest/molecularDynamicsGen2Mounted.test.tsx',
            './tests/vitest/molecularDynamicsGen2ShellRoundTrip.test.tsx',
            './tests/vitest/molstarViewerLoadStateMounted.test.tsx',
            './tests/vitest/boltzApiNativeControls.test.tsx',
            './tests/vitest/stateLandscapeWorkspacePanel.test.tsx',
            './tests/vitest/bioxpCockpitAdmissionFanoutMounted.test.tsx',
            './tests/vitest/bioxpCameraMounted.test.tsx',
            './tests/vitest/bioxpOperatorGenerationPayload.test.ts',
            './tests/vitest/bioxpOperatorCriticalControlsMounted.test.tsx',
            './tests/vitest/bioxpOperatorPipetteMounted.test.tsx',
            './tests/vitest/bioxpReceiptTerminality.test.ts',
            './tests/vitest/ontInstrumentPanel.test.tsx',
            './tests/vitest/pooledAssignmentReviewPanel.test.tsx',
            './tests/vitest/conformationalMappingViewerBehavior.test.tsx',
            './tests/vitest/frustraMpnnSettingsControls.test.tsx',
            './tests/vitest/frustraMpnnOperatorSurfaces.test.tsx',
            './tests/vitest/frustraMpnnGovernedLaunches.test.tsx',
            './tests/vitest/frustraMpnnUploadAnalysis.test.tsx',
            './tests/vitest/frustraMpnnStructureSelector.test.tsx',
            './tests/vitest/frustraMpnnExperimentResults.test.tsx',
            './tests/vitest/resultsViewerAntibodyContinuation.test.tsx',
            './tests/vitest/conformationalMappingRepairsMounted.test.tsx',
            './tests/vitest/projectManagerApi.test.ts',
            './tests/vitest/projectManagerPage.test.tsx',
            './tests/vitest/projectReturnBanner.test.tsx',
            './tests/vitest/devIssueLedgerScreenshot.test.tsx',
            './tests/vitest/ngsResultRoutingMounted.test.tsx',
            './tests/vitest/ngsWorkflowChooserMounted.test.tsx',
            './tests/vitest/ngsProjectPanelMounted.test.tsx',
            './tests/vitest/molBioProjectHubMounted.test.tsx',
            './tests/vitest/ngsPayloadMounted.test.tsx',
            './tests/vitest/readAndSignalWorkbench.test.tsx',
            './tests/vitest/ontSignalIdealComparison.test.tsx',
            './tests/vitest/ngsAlignmentAccessLifetimeMounted.test.tsx',
            './tests/vitest/ontFastqQcResultPanel.test.tsx',
            './tests/vitest/domainWorkflowOperatorClosure.test.ts',
        ],
    },
});
