#!/usr/bin/env python3
"""
Filter RFD3 outputs based on structural metrics.

Applies secondary structure and radius of gyration filters
to CIF structures generated by RFdiffusion3.
"""

import argparse
import gzip
import json
import os
import shutil
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path
from typing import Optional

# Try to import biotite for CIF parsing
try:
    from biotite.structure.io import load_structure
    from biotite.structure import filter_backbone
    import numpy as np
    HAS_BIOTITE = True
except ImportError:
    HAS_BIOTITE = False
    print("Warning: biotite not available, using basic filtering")


def calculate_radius_of_gyration(coords: 'np.ndarray') -> float:
    """Calculate radius of gyration from coordinates."""
    centroid = coords.mean(axis=0)
    distances = np.sqrt(np.sum((coords - centroid) ** 2, axis=1))
    return np.sqrt(np.mean(distances ** 2))


def count_secondary_structure(structure) -> dict:
    """
    Count secondary structure elements.
    Returns dict with 'helices', 'strands', 'total_ss'.
    """
    # Simplified SS counting based on backbone geometry
    # Full implementation would use DSSP
    return {
        'helices': 0,  # TODO: implement proper SS detection
        'strands': 0,
        'total_ss': 0
    }


def filter_structure(
    cif_path: Path,
    json_path: Optional[Path],
    output_dir: Path,
    min_ss: Optional[int] = None,
    max_ss: Optional[int] = None,
    min_helices: Optional[int] = None,
    max_helices: Optional[int] = None,
    min_strands: Optional[int] = None,
    max_strands: Optional[int] = None,
    min_rog: Optional[float] = None,
    max_rog: Optional[float] = None,
) -> dict:
    """
    Filter a single structure based on criteria.
    
    Returns dict with pass/fail status and metrics.
    """
    result = {
        'file': str(cif_path),
        'passed': True,
        'reason': None,
        'metrics': {}
    }
    
    if not HAS_BIOTITE:
        # Without biotite, just copy files through
        shutil.copy(cif_path, output_dir / cif_path.name)
        if json_path and json_path.exists():
            shutil.copy(json_path, output_dir / json_path.name)
        return result
    
    try:
        # Load structure
        if str(cif_path).endswith('.gz'):
            with gzip.open(cif_path, 'rt') as f:
                structure = load_structure(f)
        else:
            structure = load_structure(str(cif_path))
        
        # Get backbone coordinates for RoG
        backbone = filter_backbone(structure)
        coords = backbone.coord
        
        # Calculate metrics
        rog = calculate_radius_of_gyration(coords)
        ss_counts = count_secondary_structure(structure)
        
        result['metrics'] = {
            'radius_of_gyration': float(rog),
            **ss_counts
        }
        
        # Apply filters
        if min_rog is not None and rog < min_rog:
            result['passed'] = False
            result['reason'] = f"RoG {rog:.2f} < min {min_rog}"
        elif max_rog is not None and rog > max_rog:
            result['passed'] = False
            result['reason'] = f"RoG {rog:.2f} > max {max_rog}"
        
        # Copy files if passed
        if result['passed']:
            shutil.copy(cif_path, output_dir / cif_path.name)
            if json_path and json_path.exists():
                shutil.copy(json_path, output_dir / json_path.name)
                
    except Exception as e:
        result['passed'] = False
        result['reason'] = f"Error: {str(e)}"
    
    return result


def main():
    parser = argparse.ArgumentParser(
        description='Filter RFD3 outputs based on structural metrics'
    )
    parser.add_argument('--input-dir', required=True,
                        help='Directory containing CIF files')
    parser.add_argument('--output-dir', required=True,
                        help='Output directory for filtered files')
    parser.add_argument('--min-ss', type=int, default=None,
                        help='Minimum secondary structure elements')
    parser.add_argument('--max-ss', type=int, default=None,
                        help='Maximum secondary structure elements')
    parser.add_argument('--min-helices', type=int, default=None,
                        help='Minimum alpha helices')
    parser.add_argument('--max-helices', type=int, default=None,
                        help='Maximum alpha helices')
    parser.add_argument('--min-strands', type=int, default=None,
                        help='Minimum beta strands')
    parser.add_argument('--max-strands', type=int, default=None,
                        help='Maximum beta strands')
    parser.add_argument('--min-rog', type=float, default=None,
                        help='Minimum radius of gyration')
    parser.add_argument('--max-rog', type=float, default=None,
                        help='Maximum radius of gyration')
    parser.add_argument('--ncpus', type=int, default=1,
                        help='Number of parallel processes')
    
    args = parser.parse_args()
    
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find all CIF files
    cif_files = list(input_dir.glob('*.cif.gz')) + list(input_dir.glob('*.cif'))
    print(f"Found {len(cif_files)} CIF files to filter")
    
    results = []
    for cif_path in cif_files:
        # Find matching JSON
        json_path = cif_path.with_suffix('').with_suffix('.json')
        if not json_path.exists():
            json_path = None
        
        result = filter_structure(
            cif_path=cif_path,
            json_path=json_path,
            output_dir=output_dir,
            min_ss=args.min_ss,
            max_ss=args.max_ss,
            min_helices=args.min_helices,
            max_helices=args.max_helices,
            min_strands=args.min_strands,
            max_strands=args.max_strands,
            min_rog=args.min_rog,
            max_rog=args.max_rog,
        )
        results.append(result)
    
    # Summary
    passed = sum(1 for r in results if r['passed'])
    print(f"Filtering complete: {passed}/{len(results)} structures passed")
    
    # Write results to jsonl
    with open(f'rfd3_data_{os.getpid()}.jsonl', 'w') as f:
        for r in results:
            f.write(json.dumps(r) + '\n')


if __name__ == '__main__':
    main()
