#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="${BMS_HOME:-$(cd "$SCRIPT_DIR/.." && pwd)}"
COMPOSE_FILE="$PROJECT_DIR/compose.core-runtime.yml"
CONTROLLER="$SCRIPT_DIR/biomodstack_core_runtime_controller.py"
ACTION="${1:-up}"
if [ "$#" -gt 0 ]; then
    shift
fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
export PATH="/usr/local/bin:/usr/bin:/bin:$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
export BMS_HOME="$PROJECT_DIR"
export BMS_RUNTIME_MODE=container
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-biomodstack-core-runtime}"

declare -A _BMS_LAUNCH_ENV=()
while IFS= read -r key; do
    _BMS_LAUNCH_ENV["$key"]="${!key}"
done < <(compgen -A variable BMS_)

if [ -f "$HOME/.biomodstack/env.sh" ]; then
    # Compatibility profile generated by biomodstack_runtime_profile.py.
    # shellcheck disable=SC1090
    source "$HOME/.biomodstack/env.sh"
fi

load_env_file_overrides() {
    local env_file="$1"
    [ -f "$env_file" ] || return 0

    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            ''|'#'*)
                continue
                ;;
        esac
        local key="${line%%=*}"
        local value="${line#*=}"
        if [ -z "$key" ] || [ "$key" = "$line" ]; then
            continue
        fi
        export "$key=$value"
    done < "$env_file"
}

load_root_owned_mk1d_recovery_gid() {
    # This is the managed runtime source for the socket group. Do not source it:
    # require a root-owned regular file with exactly one numeric assignment.
    local recovery_env='/etc/biomodstack/mk1d-reconnect.env'
    [ -e "$recovery_env" ] || return 0
    if [ ! -f "$recovery_env" ] || [ -L "$recovery_env" ] || [ "$(stat -c '%u:%g:%a' "$recovery_env")" != '0:0:644' ]; then
        echo "BioModStack stable runtime is blocked: invalid root-owned Mk1D recovery GID file." >&2
        exit 78
    fi
    local line extra key value
    IFS= read -r line < "$recovery_env" || true
    IFS= read -r extra < <(tail -n +2 "$recovery_env") || true
    key="${line%%=*}"
    value="${line#*=}"
    if [ "$key" != 'BMS_MK1D_RECOVERY_GID' ] || [ "$value" = "$line" ] || [[ ! "$value" =~ ^[0-9]+$ ]] || [ -n "$extra" ]; then
        echo "BioModStack stable runtime is blocked: malformed Mk1D recovery GID file." >&2
        exit 78
    fi
    export BMS_MK1D_RECOVERY_GID="$value"
}

PROFILE_CORE_RUNTIME_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/biomodstack/core-runtime.env"
LEGACY_CORE_RUNTIME_ENV_FILE="$PROJECT_DIR/.env.core-runtime.local"
CORE_RUNTIME_ENV_FILE="${BMS_CORE_RUNTIME_ENV_FILE:-$PROFILE_CORE_RUNTIME_ENV_FILE}"
export BMS_CORE_RUNTIME_ENV_FILE="$CORE_RUNTIME_ENV_FILE"
compose_extra_args=()
if [ -f "$CORE_RUNTIME_ENV_FILE" ]; then
    load_env_file_overrides "$CORE_RUNTIME_ENV_FILE"
    compose_extra_args=(--env-file "$CORE_RUNTIME_ENV_FILE")
elif [ -f "$LEGACY_CORE_RUNTIME_ENV_FILE" ]; then
    load_env_file_overrides "$LEGACY_CORE_RUNTIME_ENV_FILE"
    compose_extra_args=(--env-file "$LEGACY_CORE_RUNTIME_ENV_FILE")
fi
for key in "${!_BMS_LAUNCH_ENV[@]}"; do
    # Persisted installation storage wins over a selecting Development process.
    # Explicit alternative installations use BMS_CORE_RUNTIME_ENV_FILE.
    case "$key" in
        BMS_DATA|BMS_STATE_DIR|BMS_INPUTS|BMS_DB_PATH|BMS_DB_PARENT|BMS_RESULTS_DIR|BMS_RESULTS_ROOT|BMS_CONTAINER_DIR|BMS_WEIGHTS|BMS_COLABFOLD_DB|BMS_MSA_CACHE|BMS_SABDAB_CACHE|BMS_WORK|BMS_ANALYSIS_CACHE|BMS_CONTAINER_STATE_PATH|BMS_INPUTS_CONTAINER_PATH|BMS_DB_CONTAINER_PATH)
            if [ -f "$CORE_RUNTIME_ENV_FILE" ] || [ -f "$LEGACY_CORE_RUNTIME_ENV_FILE" ]; then continue; fi
            ;;
    esac
    export "$key=${_BMS_LAUNCH_ENV[$key]}"
done
load_root_owned_mk1d_recovery_gid

if [ -z "${BMS_STATE_DIR:-}" ]; then
    echo "BioModStack stable runtime is blocked: BMS_STATE_DIR must be explicitly configured; no fallback state root is permitted." >&2
    exit 78
fi
if [ ! -d "$BMS_STATE_DIR" ]; then
    echo "BioModStack stable runtime is blocked: configured BMS_STATE_DIR is not a directory: $BMS_STATE_DIR" >&2
    exit 78
fi
export BMS_DATA="$BMS_STATE_DIR"
export BMS_DB_PARENT="$(dirname "${BMS_DB_PATH:-$BMS_STATE_DIR/biomodstack.db}")"
# Validate every configured directory bind without making directories or moving data.
# Settings save remains configuration-only; provision missing roots intentionally
# before managed startup. Docker itself also fails closed (create_host_path:false).
if [[ "$ACTION" =~ ^(supervise|preflight|up|restart)$ ]]; then
    PYTHONPATH="$PROJECT_DIR${PYTHONPATH:+:$PYTHONPATH}" python3 -c 'from biomodstack_runtime_profile import resolve_runtime_paths, validate_core_runtime_storage; validate_core_runtime_storage(resolve_runtime_paths())'
fi
export BMS_CONTAINER_STATE_PATH="${BMS_CONTAINER_STATE_PATH:-/var/lib/biomodstack}"
export BMS_API_HOST_PORT="${BMS_API_HOST_PORT:-18000}"
export BMS_WEB_HOST_PORT="${BMS_WEB_HOST_PORT:-18080}"
if [ "${BMS_WORKFLOW_ADAPTER_LANE:-}" != "production" ]; then
    echo "BioModStack stable runtime is blocked: core runtime can use only the Production workflow adapter lane." >&2
    exit 78
fi
export BMS_WORKFLOW_ADAPTER_LANE=production
export BMS_WORKFLOW_ADAPTER_URL=http://127.0.0.1:18101

if ! command -v docker >/dev/null 2>&1 || ! docker compose version >/dev/null 2>&1; then
    echo "BioModStack stable runtime requires the Docker Compose plugin; docker-compose fallback is not supported by the supervisor." >&2
    exit 78
fi
if [ ! -f "$CONTROLLER" ]; then
    echo "BioModStack runtime controller is missing: $CONTROLLER" >&2
    exit 78
fi

run_compose() {
    docker compose "${compose_extra_args[@]}" -f "$COMPOSE_FILE" "$@"
}

case "$ACTION" in
    supervise|preflight|status|up|stop|down)
        exec python3 "$CONTROLLER" "$ACTION" "$@"
        ;;
    rebuild|build)
        exec python3 "$CONTROLLER" rebuild "$@"
        ;;
    restart)
        # This is an explicit operator action, not an automatic recovery path.
        python3 "$CONTROLLER" preflight >/dev/null
        run_compose restart "$@"
        ;;
    logs)
        run_compose logs "$@"
        ;;
    ps)
        run_compose ps "$@"
        ;;
    config)
        run_compose config "$@"
        ;;
    pull)
        run_compose pull "$@"
        ;;
    *)
        echo "Usage: $0 {supervise|preflight|status|up|rebuild|build|stop|down|restart|logs|ps|config|pull} [args...]" >&2
        exit 2
        ;;
esac
