import type { ReactionRequest, ReactionPart, ReactionReagent, CyclingProgram } from '../../../../lib/goldenGateDesign';
import { Text, Num, Check, Choice } from './Fields';

export function GoldenGateReactionEditor({ value, onChange, partIds, templates }: { value: ReactionRequest; onChange: (v: ReactionRequest) => void; partIds: string[]; templates: { part: ReactionPart; reagent: ReactionReagent; cycling: CyclingProgram } }) {
  const s = value.settings;
  const settings = (patch: Partial<typeof s>) => onChange({ ...value, settings: { ...s, ...patch } });
  return <section aria-label="Reaction worksheet settings"><p>{s.schema_version}. Optional worksheet, independent of sequence design and fidelity. Unknown quantities stay unknown. Approximate dsDNA mass basis is editable; no cycling recipe is inferred.</p>
    <Num label="Mass basis (g/mol/bp)" value={s.mass_basis_g_per_mol_bp} onChange={v => settings({ mass_basis_g_per_mol_bp: v ?? NaN })} /><Choice label="Reference part" value={s.reference_part_id ?? ''} values={['', ...partIds]} onChange={v => settings({ reference_part_id: v || null })} /><Num label="Total reaction volume (uL)" value={s.total_volume_uL} onChange={total_volume_uL => settings({ total_volume_uL })} /><Num label="Reaction count" integer value={s.reaction_count} onChange={v => settings({ reaction_count: v ?? NaN })} /><Num label="Mastermix overage (%)" value={s.mastermix_overage_percent} onChange={v => settings({ mastermix_overage_percent: v ?? NaN })} /><Check label="Water in mastermix" value={s.water_in_mastermix} onChange={water_in_mastermix => settings({ water_in_mastermix })} /><Num label="Rounding increment (uL, optional)" value={s.rounding_step_uL} onChange={rounding_step_uL => settings({ rounding_step_uL })} /><Num label="Minimum transfer (uL, diagnostic only)" value={s.minimum_transfer_uL} onChange={minimum_transfer_uL => settings({ minimum_transfer_uL })} />
    <h4>DNA quantities and chemistry</h4>{value.parts.map((p, i) => {
      const set = (patch: Partial<ReactionPart>) => onChange({ ...value, parts: value.parts.map((x, j) => i === j ? { ...p, ...patch } : x) });
      const label = `Reaction DNA ${i + 1}`;
      return <fieldset key={i}><legend>{label}</legend><Choice label={`${label} part`} value={p.part_id} values={partIds} onChange={part_id => set({ part_id })} /><Num label={`${label} prepared length (bp)`} integer value={p.length_bp} onChange={length_bp => set({ length_bp })} />
        <Choice label={`${label} amount mode`} value={p.amount ? 'amount' : p.ratio_to_reference !== null ? 'ratio' : 'unknown'} values={['unknown', 'amount', 'ratio']} onChange={mode => set(mode === 'amount' ? { amount: { value: NaN, unit: 'pmol' }, ratio_to_reference: null } : mode === 'ratio' ? { amount: null, ratio_to_reference: NaN } : { amount: null, ratio_to_reference: null })} />
        {p.amount && <><Num label={`${label} amount`} value={p.amount.value} onChange={v => set({ amount: { ...p.amount!, value: v ?? NaN } })} /><Choice label={`${label} amount unit`} value={p.amount.unit} values={['ng', 'pmol']} onChange={unit => set({ amount: { ...p.amount!, unit } })} /></>}
        {p.ratio_to_reference !== null && <Num label={`${label} molar ratio`} value={p.ratio_to_reference} onChange={v => set({ ratio_to_reference: v ?? NaN })} />}
        <Check label={`${label} stock known`} value={p.stock !== null} onChange={known => set({ stock: known ? { value: NaN, unit: 'ng/uL' } : null })} />{p.stock && <><Num label={`${label} stock concentration`} value={p.stock.value} onChange={v => set({ stock: { ...p.stock!, value: v ?? NaN } })} /><Choice label={`${label} stock unit`} value={p.stock.unit} values={['ng/uL', 'pmol/uL', 'nM', 'uM']} onChange={unit => set({ stock: { ...p.stock!, unit } })} /></>}
        <Num label={`${label} dilution factor`} value={p.dilution.factor} onChange={v => set({ dilution: { ...p.dilution, factor: v ?? NaN } })} /><Num label={`${label} dilution preparation volume (uL)`} value={p.dilution.preparation_volume_uL} onChange={preparation_volume_uL => set({ dilution: { ...p.dilution, preparation_volume_uL } })} /><Check label={`${label} in mastermix`} value={p.in_mastermix} onChange={in_mastermix => set({ in_mastermix })} /><Choice label={`${label} phosphorylation`} value={p.phosphorylation} values={['unknown', 'phosphorylated', 'unphosphorylated']} onChange={phosphorylation => set({ phosphorylation })} /><Text label={`${label} purification`} value={p.purification ?? ''} onChange={v => set({ purification: v || null })} /><button type="button" onClick={() => onChange({ ...value, parts: value.parts.filter((_, j) => i !== j) })}>Remove {label}</button>
      </fieldset>;
    })}<button type="button" onClick={() => onChange({ ...value, parts: [...value.parts, structuredClone(templates.part)] })}>Add reaction DNA</button>
    <h4>Actual enzymes, ligase, buffer and additives</h4>{value.reagents.map((r, i) => {
      const set = (patch: Partial<ReactionReagent>) => onChange({ ...value, reagents: value.reagents.map((x, j) => i === j ? { ...r, ...patch } : x) }); const label = `Reagent ${i + 1}`;
      return <fieldset key={i}><legend>{label}</legend><Text label={`${label} ID`} value={r.reagent_id} onChange={reagent_id => set({ reagent_id })} /><Text label={`${label} name`} value={r.name} onChange={name => set({ name })} /><Choice label={`${label} role`} value={r.role} values={['restriction_enzyme', 'ligase', 'buffer', 'additive', 'other']} onChange={role => set({ role })} /><Text label={`${label} formulation`} value={r.formulation ?? ''} onChange={v => set({ formulation: v || null })} />
        <Choice label={`${label} volume mode`} value={r.stock_multiple !== null || r.final_multiple !== null ? 'stock dilution' : 'direct'} values={['direct', 'stock dilution']} onChange={mode => set(mode === 'direct' ? { volume_uL: null, stock_multiple: null, final_multiple: null } : { volume_uL: null, stock_multiple: NaN, final_multiple: NaN })} />
        {r.stock_multiple !== null || r.final_multiple !== null ? <><Num label={`${label} stock strength (X)`} value={r.stock_multiple} onChange={stock_multiple => set({ stock_multiple })} /><Num label={`${label} final strength (X)`} value={r.final_multiple} onChange={final_multiple => set({ final_multiple })} /></> : <Num label={`${label} volume (uL)`} value={r.volume_uL} onChange={volume_uL => set({ volume_uL })} />}
        <Check label={`${label} in mastermix`} value={r.in_mastermix} onChange={in_mastermix => set({ in_mastermix })} /><button type="button" onClick={() => onChange({ ...value, reagents: value.reagents.filter((_, j) => i !== j) })}>Remove {label}</button>
      </fieldset>;
    })}<button type="button" onClick={() => onChange({ ...value, reagents: [...value.reagents, structuredClone(templates.reagent)] })}>Add reagent</button>
    <Check label="Include explicit cycling program" value={s.cycling !== null} onChange={enabled => settings({ cycling: enabled ? structuredClone(templates.cycling) : null })} />
    {s.cycling && (() => { const c = s.cycling; const set = (cycling: CyclingProgram) => settings({ cycling }); return <fieldset><legend>User-selected cycling (not a prescribed assay)</legend><Text label="Cycling program name" value={c.name} onChange={name => set({ ...c, name })} /><Text label="Cycling provenance" value={c.provenance ?? ''} onChange={v => set({ ...c, provenance: v || null })} />{c.blocks.map((b, i) => {
      const block = (next: typeof b) => set({ ...c, blocks: c.blocks.map((x, j) => i === j ? next : x) });
      return <fieldset key={i}><legend>Cycle block {i + 1}</legend><Num label={`Block ${i + 1} repetitions`} integer value={b.repetitions} onChange={v => block({ ...b, repetitions: v ?? NaN })} />{b.steps.map((step, n) => <div key={n}><Num label={`Block ${i + 1} step ${n + 1} temperature (C)`} value={step.temperature_C} onChange={v => block({ ...b, steps: b.steps.map((x, j) => n === j ? { ...step, temperature_C: v ?? NaN } : x) })} /><Num label={`Block ${i + 1} step ${n + 1} duration (seconds)`} value={step.duration_seconds} onChange={v => block({ ...b, steps: b.steps.map((x, j) => n === j ? { ...step, duration_seconds: v ?? NaN } : x) })} /><button type="button" onClick={() => block({ ...b, steps: b.steps.filter((_, j) => n !== j) })}>Remove block {i + 1} step {n + 1}</button></div>)}<button type="button" onClick={() => block({ ...b, steps: [...b.steps, { temperature_C: NaN, duration_seconds: NaN }] })}>Add block {i + 1} step</button><button type="button" onClick={() => set({ ...c, blocks: c.blocks.filter((_, j) => i !== j) })}>Remove block {i + 1}</button></fieldset>;
    })}<button type="button" onClick={() => set({ ...c, blocks: [...c.blocks, { repetitions: 1, steps: [] }] })}>Add cycling block</button></fieldset>; })()}
  </section>;
}
