import type { FidelitySettings, DatasetChoice, SearchSettings, OverhangSearch, WindowSearch } from '../../../../lib/goldenGateDesign';
import { Text, Num, Check, Choice, Words } from './Fields';

export function GoldenGateFidelityEditor({ value, onChange, datasets }: { value: FidelitySettings; onChange: (v: FidelitySettings) => void; datasets: DatasetChoice[] }) {
  const set = (patch: Partial<FidelitySettings>) => onChange({ ...value, ...patch });
  return <section aria-label="Fidelity reference settings"><p>Estimated junction-set correctness (empirical ligation model), not yield. No dataset means unscored, not unsavable. Actual reaction chemistry is retained separately.</p><label>Reference dataset<select aria-label="Reference dataset" value={value.dataset_id ?? ''} onChange={e => set({ dataset_id: e.target.value || null })}><option value="">Unscored</option>{value.dataset_id && !datasets.some(d => d.id === value.dataset_id) && <option value={value.dataset_id}>{value.dataset_id} (not in current discovery)</option>}{datasets.map(d => <option key={d.id} value={d.id}>{d.label}</option>)}</select></label><p>{datasets.find(d => d.id === value.dataset_id)?.description}</p><Choice label="Condition use" value={value.condition_use} values={['reference', 'explicit_proxy']} onChange={condition_use => set({ condition_use })} /><Words label="Intended junction pairs (one representative per physical junction)" value={value.junctions} onChange={junctions => set({ junctions })} /><Check label="Inventory complete" value={value.inventory_complete} onChange={inventory_complete => set({ inventory_complete })} /><Check label="Include pair observations" value={value.include_pair_observations} onChange={include_pair_observations => set({ include_pair_observations })} />
    <h4>Physical end instances (5′→3′)</h4>{value.inventory.map((end, i) => { const update = (patch: Partial<typeof end>) => set({ inventory: value.inventory.map((x, j) => i === j ? { ...end, ...patch } : x) }); const label = `End ${i + 1}`; return <fieldset key={i}><legend>{label}</legend><Text label={`${label} instance ID`} value={end.instance_id} onChange={instance_id => update({ instance_id })} /><Text label={`${label} sequence (unknown if empty)`} value={end.sequence ?? ''} onChange={v => update({ sequence: v || null })} /><Text label={`${label} role`} value={end.role} onChange={role => update({ role })} /><Text label={`${label} intended junction ID`} value={end.intended_junction_id ?? ''} onChange={v => update({ intended_junction_id: v || null })} /><Text label={`${label} polarity`} value={end.polarity ?? ''} onChange={v => update({ polarity: v || null })} /><Text label={`${label} phosphorylation`} value={end.phosphorylation ?? ''} onChange={v => update({ phosphorylation: v || null })} /><Check label={`${label} removed`} value={end.removed} onChange={removed => update({ removed })} /><button type="button" onClick={() => set({ inventory: value.inventory.filter((_, j) => i !== j) })}>Remove {label}</button></fieldset>; })}<button type="button" onClick={() => set({ inventory: [...value.inventory, { instance_id: '', sequence: null, role: '', intended_junction_id: null, polarity: null, phosphorylation: null, removed: false }] })}>Add physical end</button>
  </section>;
}
export function GoldenGateSearchSettingsEditor({ value, onChange }: { value: SearchSettings; onChange: (v: SearchSettings) => void }) {
  return <fieldset><legend>Native deterministic search</legend><p>Exact enumeration when the domain fits both limits, otherwise seeded restarts. Tie-break: descending log-F_set, target-length distance, explicit choices. No global optimum claim for bounded search.</p>{(['seed', 'evaluation_budget', 'restarts', 'exact_limit', 'alternatives'] as const).map(key => <Num key={key} label={`Search ${key}`} integer value={value[key]} onChange={v => onChange({ ...value, [key]: v ?? NaN })} />)}<Check label="Suggest unique reverse-complement classes" value={value.unique_classes} onChange={unique_classes => onChange({ ...value, unique_classes })} /><Check label="Exclude palindromes from suggestions" value={value.exclude_palindromes} onChange={exclude_palindromes => onChange({ ...value, exclude_palindromes })} /><Choice label="Search ranking mode" value={value.ranking_mode} values={['empirical', 'lexicographic']} onChange={ranking_mode => onChange({ ...value, ranking_mode })} /></fieldset>;
}
export function GoldenGateOverhangSearchEditor({ value, onChange }: { value: OverhangSearch; onChange: (v: OverhangSearch) => void }) {
  return <section aria-label="Overhang set search"><Words label="Candidate domain" value={value.candidate_domain} onChange={candidate_domain => onChange({ ...value, candidate_domain })} /><Num label="Requested junction count" integer value={value.junction_count} onChange={v => onChange({ ...value, junction_count: v ?? NaN })} /><Num label="Overhang length" integer value={value.end_length} onChange={v => onChange({ ...value, end_length: v ?? NaN })} />{(['required', 'fixed', 'excluded'] as const).map(k => <Words key={k} label={`${k} overhangs`} value={value[k]} onChange={v => onChange({ ...value, [k]: v })} />)}<GoldenGateSearchSettingsEditor value={value.settings} onChange={settings => onChange({ ...value, settings })} /></section>;
}
export function GoldenGateWindowSearchEditor({ value, onChange }: { value: WindowSearch; onChange: (v: WindowSearch) => void }) {
  const set = (patch: Partial<WindowSearch>) => onChange({ ...value, ...patch });
  return <section aria-label="Target window search"><Text label="Split target DNA" multiline value={value.sequence} onChange={sequence => set({ sequence })} /><Choice label="Split target topology" value={value.topology} values={['linear', 'circular']} onChange={topology => set({ topology })} /><Num label="Split fusion length" integer value={value.end_length} onChange={v => set({ end_length: v ?? NaN })} /><p>Windows are half-open fusion-start coordinates, not payload regions. Circular start greater than end wraps; equal boundaries mean an empty window. Core preparation must exclude fusion bases; this editor does not invent split products.</p>
    {value.windows.map((w, i) => <fieldset key={i}><legend>Cut window {i + 1}</legend><Num label={`Window ${i + 1} start`} integer value={w[0]} onChange={v => set({ windows: value.windows.map((x, j) => i === j ? [v ?? NaN, w[1]] : x) })} /><Num label={`Window ${i + 1} end`} integer value={w[1]} onChange={v => set({ windows: value.windows.map((x, j) => i === j ? [w[0], v ?? NaN] : x) })} /><Num label={`Window ${i + 1} fixed position (optional)`} integer value={value.fixed_positions[i] ?? null} onChange={v => set({ fixed_positions: value.windows.map((_, j) => i === j ? v : value.fixed_positions[j] ?? null) })} /><button type="button" onClick={() => set({ windows: value.windows.filter((_, j) => i !== j), fixed_positions: value.fixed_positions.filter((_, j) => i !== j) })}>Remove window {i + 1}</button></fieldset>)}<button type="button" onClick={() => set({ windows: [...value.windows, [0, 0]], fixed_positions: [...value.windows.map((_, i) => value.fixed_positions[i] ?? null), null] })}>Add cut window</button>
    {(['fixed_overhangs', 'required', 'excluded'] as const).map(k => <Words key={k} label={`Split ${k}`} value={value[k]} onChange={v => set({ [k]: v })} />)}
    {(['min_fragment_length', 'max_fragment_length', 'target_fragment_length'] as const).map(k => <Num key={k} label={`Split ${k} (bp)`} integer value={value[k]} onChange={v => set({ [k]: k === 'min_fragment_length' ? v ?? NaN : v })} />)}
    {value.protected_regions.map((region, i) => <fieldset key={i}><legend>Protected split region {i + 1}</legend>{([0, 1] as const).map(k => <Num key={k} label={`Protected split ${i + 1} ${k === 0 ? 'start' : 'end'}`} integer value={region[k]} onChange={v => set({ protected_regions: value.protected_regions.map((x, j) => i === j ? k === 0 ? [v ?? NaN, region[1]] : [region[0], v ?? NaN] : x) })} />)}<button type="button" onClick={() => set({ protected_regions: value.protected_regions.filter((_, j) => i !== j) })}>Remove protected split {i + 1}</button></fieldset>)}<button type="button" onClick={() => set({ protected_regions: [...value.protected_regions, [0, 0]] })}>Add protected split region</button>
    {value.frame_constraints.map((frame, i) => <fieldset key={i}><legend>Frame placement constraint {i + 1} (not translation validation)</legend>{(['start', 'end', 'origin', 'phase'] as const).map((key, k) => <Num key={key} label={`Frame ${i + 1} ${key}`} integer value={frame[k]} onChange={v => { const next: typeof frame = [...frame]; next[k] = v ?? NaN; set({ frame_constraints: value.frame_constraints.map((x, j) => i === j ? next : x) }); }} />)}<button type="button" onClick={() => set({ frame_constraints: value.frame_constraints.filter((_, j) => i !== j) })}>Remove frame {i + 1}</button></fieldset>)}<button type="button" onClick={() => set({ frame_constraints: [...value.frame_constraints, [0, 0, 0, 0]] })}>Add frame constraint</button><GoldenGateSearchSettingsEditor value={value.settings} onChange={settings => set({ settings })} />
  </section>;
}
