import { useState } from 'react';
import type { GoldenGateDesignRequest, SourceChoice, PreparationChoices, Part, FragmentEnd, Feature, Tail, DigestOutcome } from '../../../../lib/goldenGateDesign';
import type { PrimerTmOptionsResponse } from '../../../../lib/api';
import { PrimerTmSettingsPanel } from '../../PrimerTmSettingsPanel';
import { Text, Num, Check, Choice, RegionFields, RegionList, Indices } from './Fields';

function EndFields({ label, value, onChange }: { label: string; value: FragmentEnd; onChange: (v: FragmentEnd) => void }) {
  return <fieldset><legend>{label}: physical protruding strand 5′→3′</legend><Choice label={`${label} type`} value={value.type} values={['blunt', 'sticky_5', 'sticky_3']} onChange={type => onChange({ ...value, type })} /><Text label={`${label} overhang`} value={value.overhang} onChange={overhang => onChange({ ...value, overhang })} /><Text label={`${label} label`} value={value.label ?? ''} onChange={label => onChange({ ...value, label: label || null })} /><Choice label={`${label} protruding strand`} value={value.protruding_strand ?? ''} values={['', 'top', 'bottom']} onChange={v => onChange({ ...value, protruding_strand: v || null })} /></fieldset>;
}
function TailFields({ label, value, onChange }: { label: string; value: Tail; onChange: (v: Tail) => void }) {
  return <fieldset><legend>{label}</legend>{(['clamp', 'spacer', 'fusion'] as const).map(k => <Text key={k} label={`${label} ${k}`} value={value[k]} onChange={v => onChange({ ...value, [k]: v })} />)}</fieldset>;
}
function FeatureFields({ value, onChange }: { value: Feature[]; onChange: (v: Feature[]) => void }) {
  return <details><summary>Source features ({value.length})</summary>{value.map((f, i) => {
    const set = (v: Feature) => onChange(value.map((x, j) => i === j ? v : x));
    return <fieldset key={i}><legend>Feature {i + 1}</legend><Text label={`Feature ${i + 1} ID`} value={f.id} onChange={id => set({ ...f, id })} /><Text label={`Feature ${i + 1} type`} value={f.type} onChange={type => set({ ...f, type })} /><Text label={`Feature ${i + 1} name`} value={f.name} onChange={name => set({ ...f, name })} /><RegionList label={`Feature ${i + 1} segments`} value={f.segments} onChange={segments => set({ ...f, segments })} /><Choice label={`Feature ${i + 1} strand`} value={String(f.strand)} values={['-1', '0', '1']} onChange={v => set({ ...f, strand: Number(v) as -1 | 0 | 1 })} /><Choice label={`Feature ${i + 1} codon start`} value={f.codon_start === null ? '' : String(f.codon_start)} values={['', '1', '2', '3']} onChange={v => set({ ...f, codon_start: v ? Number(v) as 1 | 2 | 3 : null })} /><p>Status: {f.status}; frame preserved: {String(f.frame_preserved ?? 'unknown')}. Imported qualifiers are retained unchanged.</p><button type="button" onClick={() => onChange(value.filter((_, j) => j !== i))}>Remove feature {i + 1}</button></fieldset>;
  })}<button type="button" onClick={() => onChange([...value, { id: '', type: '', name: '', segments: [], strand: 1, qualifiers: {}, codon_start: null, status: 'intact', frame_preserved: null }])}>Add feature</button></details>;
}

export interface GoldenGatePartsEditorProps {
  value: GoldenGateDesignRequest;
  onChange: (value: GoldenGateDesignRequest) => void;
  sourceChoices: SourceChoice[];
  preparationChoices: PreparationChoices;
  enzymeChoices: GoldenGateDesignRequest['enzyme'][];
  tmOptions: PrimerTmOptionsResponse | null;
  /** Only current-request digests; the parent must not pass stale preview data. */
  digests?: DigestOutcome[];
}
export function GoldenGatePartsEditor({ value, onChange, sourceChoices, preparationChoices, enzymeChoices, tmOptions, digests = [] }: GoldenGatePartsEditorProps) {
  const [sourceChoice, setSourceChoice] = useState('');
  const [newSourceId, setNewSourceId] = useState('');
  const [partSource, setPartSource] = useState('');
  const [newPartId, setNewPartId] = useState('');
  const [newKind, setNewKind] = useState<Part['preparation']['kind']>('donor');
  const setPart = (i: number, part: Part) => onChange({ ...value, parts: value.parts.map((p, j) => i === j ? part : p) });
  const move = (i: number, delta: number) => { const parts = [...value.parts]; const j = i + delta; if (j < 0 || j >= parts.length) return; [parts[i], parts[j]] = [parts[j], parts[i]]; onChange({ ...value, parts }); };
  return <section aria-label="Raw parts design" className="space-y-4">
    <p>Explicit raw preparation · {value.schema_version}. Existing manual/prepared assembly remains a separate mode. No automatic design or source save.</p>
    <label>Catalog enzyme<select aria-label="Catalog enzyme" value={value.enzyme.enzyme_id} onChange={e => { const binding = enzymeChoices.find(x => x.enzyme_id === e.target.value); if (binding) onChange({ ...value, enzyme: { ...binding } }); }}><option value={value.enzyme.enzyme_id}>{value.enzyme.enzyme_id}</option>{enzymeChoices.filter(e => e.enzyme_id !== value.enzyme.enzyme_id).map(e => <option key={e.enzyme_id}>{e.enzyme_id}</option>)}</select></label><p>Catalog: {value.enzyme.catalog_id} · {value.enzyme.catalog_sha256}</p>
    <Choice label="Product topology" value={value.target.topology} values={['linear', 'circular']} onChange={topology => onChange({ ...value, target: { ...value.target, topology } })} /><Num label="Product display origin (bp)" integer min={0} value={value.target.display_origin} onChange={v => onChange({ ...value, target: { ...value.target, display_origin: v ?? NaN } })} /><Text label="Exact target DNA (optional)" multiline value={value.target.exact_sequence ?? ''} onChange={v => onChange({ ...value, target: { ...value.target, exact_sequence: v || null } })} />
    <h3>Source material</h3>
    {value.sources.map((s, i) => <fieldset key={s.id} className="border border-slate-600 p-3"><legend>{s.id}</legend>{s.source.kind === 'molecular_revision' ? <p>Immutable revision: {s.source.revision_id}. Material and annotations are resolved by the native owner; not an editable sequence projection.</p> : <>
      <Text label={`${s.id} DNA`} multiline value={s.source.sequence} onChange={sequence => { if (s.source.kind === 'inline') onChange({ ...value, sources: value.sources.map((x, j) => i === j ? { ...s, source: { ...s.source, sequence } } : x) }); }} />
      <Choice label={`${s.id} source topology`} value={s.source.topology} values={['linear', 'circular']} onChange={topology => { if (s.source.kind === 'inline') onChange({ ...value, sources: value.sources.map((x, j) => i === j ? { ...s, source: { ...s.source, topology } } : x) }); }} />
      <FeatureFields value={s.source.features} onChange={features => { if (s.source.kind === 'inline') onChange({ ...value, sources: value.sources.map((x, j) => i === j ? { ...s, source: { ...s.source, features } } : x) }); }} />
    </>}<button type="button" onClick={() => onChange({ ...value, sources: value.sources.filter((_, j) => j !== i) })}>Remove source {s.id}</button></fieldset>)}
    <fieldset><legend>Add source explicitly</legend><Text label="New source ID" value={newSourceId} onChange={setNewSourceId} /><label>Saved revision or editor snapshot<select aria-label="Source choice" value={sourceChoice} onChange={e => setSourceChoice(e.target.value)}><option value="">Select source</option>{sourceChoices.map((c, i) => <option key={i} value={String(i)}>{c.label} ({c.source.source.kind})</option>)}</select></label><button type="button" disabled={!newSourceId || sourceChoice === ''} onClick={() => { const c = sourceChoices[Number(sourceChoice)]; if (c) onChange({ ...value, sources: [...value.sources, { ...structuredClone(c.source), id: newSourceId }] }); }}>Add selected source</button><button type="button" disabled={!newSourceId} onClick={() => onChange({ ...value, sources: [...value.sources, { id: newSourceId, source: { kind: 'inline', sequence: '', topology: 'linear', features: [] } }] })}>Add inline DNA source</button></fieldset>
    <h3>Ordered part instances</h3>
    {value.parts.map((p, i) => {
      const prep = p.preparation; const setPrep = (preparation: Part['preparation']) => setPart(i, { ...p, preparation });
      const digest = digests.find(d => d.part_id === p.id);
      return <fieldset key={p.id} className="border border-slate-600 p-3"><legend>{i + 1}. {p.id}</legend><Text label={`${p.id} name`} value={p.name} onChange={name => setPart(i, { ...p, name })} /><Choice label={`${p.id} source`} value={p.source_id} values={value.sources.map(s => s.id)} onChange={source_id => setPart(i, { ...p, source_id })} /><Text label={`${p.id} role`} value={p.role ?? ''} onChange={role => setPart(i, { ...p, role: role || null })} /><Text label={`${p.id} slot`} value={p.slot ?? ''} onChange={slot => setPart(i, { ...p, slot: slot || null })} /><Choice label={`${p.id} orientation`} value={p.orientation} values={['forward', 'reverse']} onChange={orientation => setPart(i, { ...p, orientation })} /><Choice label={`${p.id} preparation`} value={prep.kind} values={['donor', 'pcr', 'synthesis', 'prepared']} onChange={kind => setPrep(structuredClone(preparationChoices[kind]))} />
        {prep.kind === 'donor' && <Num label={`${p.id} retained fragment index`} min={0} integer value={prep.retained_fragment_index} onChange={v => setPrep({ ...prep, retained_fragment_index: v ?? NaN })} />}
        {(prep.kind === 'pcr' || prep.kind === 'synthesis') && <><RegionFields label={`${p.id} payload region`} value={prep.region} onChange={region => setPrep({ ...prep, region })} /><p>Payload excludes the supplied fusion bases. Fusion strings use the final top-reference axis; right physical protrusion is its reverse complement. Clamps/spacers are explicit choices, not vendor activity guarantees.</p><TailFields label={`${p.id} left`} value={prep.left} onChange={left => setPrep({ ...prep, left })} /><TailFields label={`${p.id} right`} value={prep.right} onChange={right => setPrep({ ...prep, right })} />{prep.kind === 'pcr' && <><Num label={`${p.id} forward anneal length`} integer min={8} value={prep.forward_anneal_length} onChange={v => setPrep({ ...prep, forward_anneal_length: v ?? NaN })} /><Num label={`${p.id} reverse anneal length`} integer min={8} value={prep.reverse_anneal_length} onChange={v => setPrep({ ...prep, reverse_anneal_length: v ?? NaN })} /><Num label={`${p.id} QC minimum binding length`} integer min={1} value={prep.qc_min_binding_anneal_length} onChange={v => setPrep({ ...prep, qc_min_binding_anneal_length: v ?? NaN })} /><p>Explicit frozen footprints. Automatic footprint search is not implemented by this core leaf.</p></>}</>}
        {prep.kind === 'prepared' ? <><EndFields label={`${p.id} left end`} value={prep.left_end} onChange={left_end => setPrep({ ...prep, left_end })} /><EndFields label={`${p.id} right end`} value={prep.right_end} onChange={right_end => setPrep({ ...prep, right_end })} /></> : <><Indices label={`${p.id} removed fragment indices`} value={prep.removed_fragment_indices} onChange={removed_fragment_indices => setPrep({ ...prep, removed_fragment_indices })} /><p>Unremoved dropout fragments remain reactive background; no purification is inferred.</p>{digest?.fragments.map((f, n) => <div key={n}>Fragment {n}: {f.top_strand_sequence.length} bp <code>{f.top_strand_sequence}</code>{prep.kind === 'donor' && <button type="button" onClick={() => setPrep({ ...prep, retained_fragment_index: n })}>Retain {p.id} fragment {n}</button>}<Check label={`Remove ${p.id} fragment ${n} from reaction`} value={prep.removed_fragment_indices.includes(n)} onChange={remove => setPrep({ ...prep, removed_fragment_indices: remove ? [...new Set([...prep.removed_fragment_indices, n])] : prep.removed_fragment_indices.filter(x => x !== n) })} /></div>)}</>}
        <button type="button" onClick={() => move(i, -1)}>Move {p.id} earlier</button> <button type="button" onClick={() => move(i, 1)}>Move {p.id} later</button> <button type="button" onClick={() => onChange({ ...value, parts: value.parts.filter((_, j) => j !== i) })}>Remove part {p.id}</button>
      </fieldset>;
    })}
    <fieldset><legend>Add a part instance (sources may be reused)</legend><Text label="New part ID" value={newPartId} onChange={setNewPartId} /><Choice label="New part source" value={partSource} values={value.sources.map(s => s.id)} onChange={setPartSource} /><Choice label="New part preparation" value={newKind} values={['donor', 'pcr', 'synthesis', 'prepared']} onChange={setNewKind} /><button type="button" disabled={!newPartId || !partSource} onClick={() => onChange({ ...value, parts: [...value.parts, { id: newPartId, name: newPartId, source_id: partSource, role: null, slot: null, orientation: 'forward', preparation: structuredClone(preparationChoices[newKind]) }] })}>Add part</button><p>Preparation templates are caller-supplied recommendations; inspect every explicit value before design.</p></fieldset>
    <details><summary>Shared primer thermodynamics</summary><p>Requested algorithm: {value.primer_settings.algorithm}; salt correction: {value.primer_settings.salt_correction}. Discovery never replaces these values.</p><PrimerTmSettingsPanel sequenceType="dna" settings={value.primer_settings} options={tmOptions} onChange={primer_settings => onChange({ ...value, primer_settings })} /></details>
  </section>;
}
