import type { DomesticationSettings, CDSConstraint, UnwantedSite } from '../../../../lib/goldenGateDesign';
import { Text, Num, Check, Choice, RegionFields, RegionList, Words, Indices } from './Fields';

export function GoldenGateDomesticationEditor({ value, onChange, featureIds, siteChoices, cdsTemplate }: { value: DomesticationSettings; onChange: (v: DomesticationSettings) => void; featureIds: string[]; siteChoices: UnwantedSite[]; cdsTemplate: CDSConstraint }) {
  const set = (patch: Partial<DomesticationSettings>) => onChange({ ...value, ...patch });
  return <section aria-label="Domestication settings"><p>{value.schema_version}. Proposals only: original sources never change. Applying a proposal is a separate explicit action. Partial boundary codons are preserved; compound/spliced CDS are not supported by this leaf.</p><Check label="Request domestication proposals" value={value.enabled} onChange={enabled => set({ enabled })} />
    <p>Algorithm: {value.algorithm} (deterministic minimal substitutions; no random seed).</p><Num label="Domestication candidate budget" integer min={1} value={value.candidate_budget} onChange={v => set({ candidate_budget: v ?? NaN })} /><Num label="Maximum substitutions (optional)" integer min={0} value={value.max_edits} onChange={max_edits => set({ max_edits })} /><RegionList label="Editable regions" value={value.editable_regions} onChange={editable_regions => set({ editable_regions })} /><RegionList label="Protected regions" value={value.protected_regions} onChange={protected_regions => set({ protected_regions })} />
    <h4>Requested unwanted sites</h4>{value.unwanted_sites.map((site, i) => <fieldset key={i}><legend>{site.enzyme_id}</legend><Text label={`Unwanted enzyme ${i + 1} identity`} value={site.enzyme_id} onChange={enzyme_id => set({unwanted_sites:value.unwanted_sites.map((x,j)=>i===j?{...site,enzyme_id}:x)})}/><Text label={`Unwanted enzyme ${i + 1} recognition sequence`} value={site.recognition_sequence} onChange={recognition_sequence=>set({unwanted_sites:value.unwanted_sites.map((x,j)=>i===j?{...site,recognition_sequence}:x)})}/><Check label={`${site.enzyme_id} remove all occurrences`} value={site.starts === null} onChange={all => set({ unwanted_sites: value.unwanted_sites.map((x, j) => i === j ? { ...site, starts: all ? null : [] } : x) })} />{site.starts !== null && <Indices label={`${site.enzyme_id} selected site starts (0-based)`} value={site.starts} onChange={starts => set({ unwanted_sites: value.unwanted_sites.map((x, j) => i === j ? { ...site, starts } : x) })} />}<button type="button" onClick={() => set({ unwanted_sites: value.unwanted_sites.filter((_, j) => i !== j) })}>Remove unwanted enzyme {site.enzyme_id}</button></fieldset>)}
    <label>Add catalog enzyme<select aria-label="Add unwanted catalog enzyme" value="" onChange={e => { const site = siteChoices.find(s => s.enzyme_id === e.target.value); if (site) set({ unwanted_sites: [...value.unwanted_sites, structuredClone(site)] }); }}><option value="">Select enzyme</option>{siteChoices.map(s => <option key={s.enzyme_id}>{s.enzyme_id}</option>)}</select></label>
    <button type="button" onClick={()=>set({unwanted_sites:[...value.unwanted_sites,{enzyme_id:'',recognition_sequence:'',starts:null}]})}>Add explicit unwanted motif</button><h4>CDS constraints</h4>{value.cds.map((c, i) => {
      const update = (patch: Partial<CDSConstraint>) => set({ cds: value.cds.map((x, j) => i === j ? { ...c, ...patch } : x) }); const label = `CDS ${i + 1}`;
      return <fieldset key={i}><legend>{label}</legend><Text label={`${label} feature ID`} value={c.feature_id} onChange={feature_id=>update({feature_id})}/><Choice label={`${label} feature`} value={c.feature_id} values={featureIds} onChange={feature_id => update({ feature_id })} /><RegionFields label={`${label} region`} value={c.region} onChange={region => update({ region })} /><Choice label={`${label} strand`} value={String(c.strand)} values={['1', '-1']} onChange={v => update({ strand: Number(v) as 1 | -1 })} /><Choice label={`${label} frame (5-prime skipped bases)`} value={String(c.frame)} values={['0', '1', '2']} onChange={v => update({ frame: Number(v) as 0 | 1 | 2 })} /><Num label={`${label} NCBI genetic code`} integer value={c.genetic_code} onChange={v => update({ genetic_code: v ?? NaN })} /><Choice label={`${label} initiation policy`} value={c.initiation} values={['ordinary', 'preserve', 'allowed']} onChange={initiation => update({ initiation })} /><Words label={`${label} allowed start codons`} value={c.allowed_start_codons} onChange={allowed_start_codons => update({ allowed_start_codons })} /><Choice label={`${label} stop policy`} value={c.stop_policy} values={['preserve', 'synonymous']} onChange={stop_policy => update({ stop_policy })} /><button type="button" onClick={() => set({ cds: value.cds.filter((_, j) => i !== j) })}>Remove {label}</button></fieldset>;
    })}<button type="button" onClick={() => set({ cds: [...value.cds, structuredClone(cdsTemplate)] })}>Add CDS constraint</button>
    <Text label="Edit objective" value="Minimum substitutions; no codon optimization" readOnly />
  </section>;
}
