import { useState } from 'react';
import { fetchRestrictionCatalogBrowse } from '../../../../lib/restrictionAnalysis';
import { useQuery } from '@tanstack/react-query';
import { fetchNucleotideSequences, fetchMolBioSequenceRevisions, type PrimerTmOptionsResponse } from '../../../../lib/api';
import type { WorkflowRequest, AssembleTask, PrimerSelectionSettings } from '../../../../lib/goldenGateWorkflowTypes';
import type { DigestOutcome, SourceChoice, PreparationChoices, GoldenGateDesignRequest, DatasetChoice, ReactionPart, ReactionReagent, CDSConstraint } from '../../../../lib/goldenGateDesign';
import * as defaults from '../../../../lib/goldenGateWorkflowDefaults';
import { GoldenGatePartsEditor } from './GoldenGatePartsEditor';
import { GoldenGateFidelityEditor, GoldenGateOverhangSearchEditor, GoldenGateWindowSearchEditor } from './GoldenGateFidelityEditor';
import { GoldenGateDomesticationEditor } from './GoldenGateDomesticationEditor';
import { GoldenGateReactionEditor } from './GoldenGateReactionEditor';
import { Choice, Num, Text, Check } from './Fields';

export const preparationChoices: PreparationChoices = {
  donor: { kind: 'donor', retained_fragment_index: 0, removed_fragment_indices: [] },
  prepared: { kind: 'prepared', left_end: { type: 'blunt', overhang: '', label: null, protruding_strand: null }, right_end: { type: 'blunt', overhang: '', label: null, protruding_strand: null } },
  synthesis: { kind: 'synthesis', region: { start: 0, end: 0, wraps_origin: false }, left: { clamp: '', spacer: '', fusion: '' }, right: { clamp: '', spacer: '', fusion: '' }, removed_fragment_indices: [] },
  pcr: { kind: 'pcr', region: { start: 0, end: 0, wraps_origin: false }, left: { clamp: '', spacer: '', fusion: '' }, right: { clamp: '', spacer: '', fusion: '' }, forward_anneal_length: 20, reverse_anneal_length: 20, qc_min_binding_anneal_length: 12, removed_fragment_indices: [] },
};
export function initialWorkflow(task: WorkflowRequest['task'], core: GoldenGateDesignRequest): WorkflowRequest {
 const common = { schema_version: 'bms.golden-gate-design.v1' as const, fidelity: { ...defaults.fidelitySettingsDefaults } };
 if (task === 'assemble_parts') return { ...core, ...common, task, automatic_primers: [], domestication: [], reaction: null };
 if (task === 'evaluate_overhangs') return { ...common, task, junctions: [], inventory: [], inventory_complete: false };
 if (task === 'optimize_overhangs') return { ...common, task, candidate_domain: [], junction_count: 2, end_length: 4, fixed: [], required: [], excluded: [], search: { ...defaults.searchControlsDefaults } };
 return { ...common, task, target: structuredClone(core.sources[0] ?? { id: 'target', source: { kind: 'inline', sequence: '', topology: 'linear', features: [] } }), enzyme: core.enzyme, windows: [], fixed_positions: [], fixed_overhangs: [], required: [], excluded: [], protected_regions: [], frame_constraints: [], min_fragment_length: 1, max_fragment_length: null, target_fragment_length: null, display_origin: 0, preparation: { kind: 'synthesis', clamp: '', spacer: '', forward_anneal_length: 20, reverse_anneal_length: 20, qc_min_binding_anneal_length: 12 }, terminal_right_fusion: null, primer_settings: core.primer_settings, search: { ...defaults.searchControlsDefaults }, reaction: null };
}
export function GoldenGateWorkflowControls({ value: r, onChange, sourceChoices, enzymes, datasets, tmOptions, digests = [] }: {
 digests?: DigestOutcome[];
 value: WorkflowRequest; onChange: (v: WorkflowRequest) => void; sourceChoices: SourceChoice[];
 enzymes: GoldenGateDesignRequest['enzyme'][]; datasets: DatasetChoice[]; tmOptions: PrimerTmOptionsResponse | null;
}) {
 const [editOpen,setEditOpen] = useState(false);
 const catalog = useQuery({queryKey:['molbio-restriction-catalog'],queryFn:({signal})=>fetchRestrictionCatalogBrowse({signal}),enabled:editOpen,staleTime:300000});
 const [browse, setBrowse] = useState(false); const [search, setSearch] = useState(''); const [page, setPage] = useState(0); const [sequenceId, setSequenceId] = useState('');
 const sequences = useQuery({ queryKey: ['nucleotide-sequences', 'gg-source', search, page], queryFn: async () => (await fetchNucleotideSequences({ search, limit: 50, offset: page * 50 })).data, enabled: browse, staleTime: 300000 });
 const revisions = useQuery({ queryKey: ['molbio-sequence-revisions', sequenceId], queryFn: async () => (await fetchMolBioSequenceRevisions(sequenceId)).data, enabled: !!sequenceId, staleTime: 300000 });
 const choices: SourceChoice[] = [...sourceChoices, ...(revisions.data ?? []).map(rev => ({ label: `${sequenceId} revision ${rev.revision_number} (${rev.content_length} bp)`, source: { id: rev.revision_id, source: { kind: 'molecular_revision' as const, revision_id: rev.revision_id } } }))];
 const fidelity = { ...r.fidelity, junctions: r.task === 'evaluate_overhangs' ? r.junctions : [], inventory: r.task === 'evaluate_overhangs' ? r.inventory : [], inventory_complete: r.task === 'evaluate_overhangs' && r.inventory_complete };
 const sourceUI = <details onToggle={e => setBrowse(e.currentTarget.open)}><summary>Browse saved source revisions / next-stage products</summary><Text label="Source library search" value={search} onChange={v => { setSearch(v); setPage(0); }} /><Choice label="Saved source sequence" value={sequenceId} values={['', ...(sequences.data ?? []).map(s => s.id)]} onChange={setSequenceId} />{sequences.data?.map(s => <p key={s.id}>{s.id}: {s.name}</p>)}<button disabled={!page} onClick={() => setPage(page - 1)}>Previous sources</button><button disabled={sequences.data?.length !== 50} onClick={() => setPage(page + 1)}>More sources</button>{(sequences.error || revisions.error) && <p role="alert">Could not read sources: {String(sequences.error || revisions.error)}</p>}</details>;
 const setPhysical = (patch: { reaction: AssembleTask['reaction'] }) => onChange({ ...r, ...patch } as WorkflowRequest);
 return <div className="space-y-3">
 {(r.task === 'assemble_parts' || r.task === 'split_target') && sourceUI}
 {r.task === 'assemble_parts' && <GoldenGatePartsEditor digests={digests} value={r} onChange={core => onChange({ ...r, ...core })} sourceChoices={choices} enzymeChoices={enzymes} preparationChoices={preparationChoices} tmOptions={tmOptions} />}
 {r.task === 'split_target' && <>
 <GoldenGatePartsEditor targetOnly value={{ schema_version: r.schema_version, task: 'assemble_parts', sources: [r.target], parts: [], enzyme: r.enzyme, target: { topology: r.target.source.kind === 'inline' ? r.target.source.topology : 'linear', display_origin: r.display_origin, exact_sequence: null }, primer_settings: r.primer_settings }} onChange={core => onChange({ ...r, target: core.sources.at(-1) ?? r.target, enzyme: core.enzyme, display_origin: core.target.display_origin, primer_settings: core.primer_settings })} sourceChoices={choices} enzymeChoices={enzymes} preparationChoices={preparationChoices} tmOptions={tmOptions} />
 <p>The split target is the last explicitly selected source. Its own topology is authoritative; immutable revisions retain their topology. Fragment preparation is set below.</p>
 <Num label="Split display origin" min={0} integer value={r.display_origin} onChange={v => onChange({...r,display_origin:v ?? NaN})} /><GoldenGateWindowSearchEditor nativeWorkflow value={{ sequence: r.target.source.kind === 'inline' ? r.target.source.sequence : '', topology: r.target.source.kind === 'inline' ? r.target.source.topology : 'linear', end_length: 4, windows: r.windows.map(w => [w.start,w.end]), fixed_positions: r.fixed_positions, fixed_overhangs: r.fixed_overhangs, required: r.required, excluded: r.excluded, protected_regions: r.protected_regions.map(w => [w.start,w.end]), frame_constraints: r.frame_constraints.map(w => [w.start,w.end,w.origin,w.phase]), min_fragment_length: r.min_fragment_length, max_fragment_length: r.max_fragment_length, target_fragment_length: r.target_fragment_length, settings: r.search }} onChange={v => onChange({ ...r, target: r.target.source.kind === 'inline' ? { ...r.target, source: { ...r.target.source, sequence: v.sequence, topology: v.topology } } : r.target, windows: v.windows.map(([start,end]) => ({start,end})), fixed_positions: v.fixed_positions, fixed_overhangs: v.fixed_overhangs, required: v.required, excluded: v.excluded, protected_regions: v.protected_regions.map(([start,end]) => ({start,end})), frame_constraints: v.frame_constraints.map(([start,end,origin,phase]) => ({start,end,origin,phase: phase as 0|1|2})), min_fragment_length: v.min_fragment_length, max_fragment_length: v.max_fragment_length, target_fragment_length: v.target_fragment_length, search: v.settings })} />
 <Choice label="Split preparation" value={r.preparation.kind} values={['pcr','synthesis']} onChange={kind => onChange({...r, preparation: {...r.preparation,kind}})} />
 {(['clamp','spacer'] as const).map(k => <Text key={k} label={`Split ${k}`} value={r.preparation[k]} onChange={v => onChange({...r, preparation:{...r.preparation,[k]:v}})} />)}
 {(['forward_anneal_length','reverse_anneal_length','qc_min_binding_anneal_length'] as const).map(k => <Num key={k} label={`Split ${k}`} value={r.preparation[k]} integer min={k === 'qc_min_binding_anneal_length' ? 1 : 8} onChange={v => onChange({...r,preparation:{...r.preparation,[k]:v ?? NaN}})} />)}
 <Text label="Linear terminal right fusion" value={r.terminal_right_fusion ?? ''} onChange={v => onChange({...r,terminal_right_fusion:v || null})} />
 </>}
 <details><summary>Empirical reference / evaluation</summary><GoldenGateFidelityEditor evaluation={r.task === 'evaluate_overhangs'} value={fidelity} datasets={datasets} onChange={v => { const f = {dataset_id:v.dataset_id,condition_use:v.condition_use,include_pair_observations:v.include_pair_observations}; onChange(r.task === 'evaluate_overhangs' ? {...r,fidelity:f,junctions:v.junctions,inventory:v.inventory,inventory_complete:v.inventory_complete} : {...r,fidelity:f}); }} /></details>
 {r.task === 'optimize_overhangs' && <GoldenGateOverhangSearchEditor value={{...r,settings:r.search}} onChange={v => onChange({...r,candidate_domain:v.candidate_domain,junction_count:v.junction_count,end_length:v.end_length as 3|4,fixed:v.fixed,required:v.required,excluded:v.excluded,search:v.settings})} />}
 {r.task === 'assemble_parts' && <details><summary>Automatic primer selection</summary><p>Uses the shared native designer; requested ranges remain separate from effective fixed footprints.</p>{r.parts.filter(p => p.preparation.kind === 'pcr').map(p => { const a = r.automatic_primers.find(a => a.part_id === p.id); return <fieldset key={p.id}><legend>{p.id}</legend><Check label={`Automatic primers ${p.id}`} value={!!a} onChange={yes => onChange({...r,automatic_primers:yes ? [...r.automatic_primers,{part_id:p.id,pair_rank:1,settings:{...defaults.primerSelectionSettingsDefaults}}] : r.automatic_primers.filter(x => x.part_id !== p.id)})} />{a && <><Num label={`${p.id} pair rank`} min={1} integer value={a.pair_rank} onChange={v => onChange({...r,automatic_primers:r.automatic_primers.map(x => x === a ? {...a,pair_rank:v ?? NaN} : x)})} />{(Object.keys(defaults.primerSelectionSettingsDefaults) as (keyof PrimerSelectionSettings)[]).map(k => <Num key={k} label={`${p.id} ${k}`} value={a.settings[k]} onChange={v => onChange({...r,automatic_primers:r.automatic_primers.map(x => x === a ? {...a,settings:{...a.settings,[k]:v ?? NaN}} : x)})} />)}</>}</fieldset>; })}</details>}
 {r.task === 'assemble_parts' && <details onToggle={e=>setEditOpen(e.currentTarget.open)}><summary>Explicit domestication proposals</summary>{r.sources.map(s => { const e = r.domestication.find(e => e.source_id === s.id); return <fieldset key={s.id}><legend>{s.id}</legend><button onClick={() => onChange({...r,domestication:e ? r.domestication.filter(x => x !== e) : [...r.domestication,{source_id:s.id,settings:structuredClone(defaults.domesticationSettingsDefaults) as unknown as AssembleTask['domestication'][number]['settings'],accepted_sequence:null}]})}>{e ? 'Remove' : 'Add'} edit request {s.id}</button>{e && <GoldenGateDomesticationEditor value={e.settings} onChange={settings => onChange({...r,domestication:r.domestication.map(x => x === e ? {...e,settings,accepted_sequence:null} : x)})} featureIds={s.source.kind === 'inline' ? s.source.features.map(f => f.id) : e.settings.cds.map(c => c.feature_id)} siteChoices={(catalog.data?.items ?? []).map(e=>({enzyme_id:e.enzyme_id,recognition_sequence:e.site_iupac,starts:null}))} cdsTemplate={{...defaults.cDSConstraintDefaults,feature_id:'',region:{start:0,end:0,wraps_origin:false}} as unknown as CDSConstraint} />}</fieldset>; })}</details>}
 {(r.task === 'assemble_parts' || r.task === 'split_target') && <details><summary>Optional reaction worksheet</summary><Check label="Calculate reaction worksheet" value={!!r.reaction} onChange={v => setPhysical({reaction:v ? {settings:{...defaults.reactionSettingsDefaults},parts:[],reagents:[]} : null})} />{r.reaction && <GoldenGateReactionEditor value={r.reaction} onChange={reaction => setPhysical({reaction})} partIds={r.task === 'assemble_parts' ? r.parts.map(p => p.id) : Array.from({length:r.windows.length+(r.target.source.kind === 'inline' && r.target.source.topology === 'circular' ? 0 : 1)},(_,i)=>`part-${i+1}`)} templates={{part:{...defaults.reactionPartDefaults,part_id:''} as ReactionPart,reagent:{...defaults.reactionReagentDefaults,reagent_id:'',name:'',role:'other'} as ReactionReagent,cycling:{name:'',provenance:null,blocks:[]}}} />}</details>}
 </div>;
}
