import { useState, type ReactNode } from 'react';
import type { GoldenGateDesignResult, Solution, Feature, FidelityResult, DomesticationResult, ReactionResult, ReactionRow } from '../../../../lib/goldenGateDesign';

function Messages({ values }: { values: string[] }) { return <ul>{values.map((s, i) => <li key={i}>{s}</li>)}</ul>; }
function Features({ features }: { features: Feature[] }) { return <table><caption>Mapped annotations · 0-based half-open locations in biological order</caption><thead><tr><th>Name / ID</th><th>Type</th><th>Segments</th><th>Strand</th><th>CDS codon start</th><th>Status / frame preserved</th><th>Qualifiers</th></tr></thead><tbody>{features.map(f => <tr key={f.id}><td>{f.name} / {f.id}</td><td>{f.type}</td><td>{f.segments.map(r => `${r.start}–${r.end}${r.wraps_origin ? ' wraps' : ''}`).join(', ')}</td><td>{f.strand}</td><td>{f.codon_start ?? 'unknown'}</td><td>{f.status} / {String(f.frame_preserved ?? 'unknown')}</td><td>{Object.entries(f.qualifiers).map(([k, v]) => <div key={k}>{k}: {Array.isArray(v) ? v.map(String).join('; ') : String(v)}</div>)}</td></tr>)}</tbody></table>; }
function Reveal({ label, children }: { label: string; children: () => ReactNode }) { const [open, setOpen] = useState(false); return <section><button type="button" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? 'Hide' : 'Show'} {label}</button>{open && children()}</section>; }
export interface GoldenGateDesignResultsProps {
  result: GoldenGateDesignResult;
  selectedSolutionId: string | null;
  onSelect: (id: string) => void;
  onLoadProduct?: (product: Solution) => void;
  /** Bind the existing shared sequence view at its lazy render boundary. */
  renderSequence?: (product: Solution) => ReactNode;
  fidelity?: FidelityResult | null;
}
export function GoldenGateDesignResults({ result: r, selectedSolutionId, onSelect, onLoadProduct, renderSequence, fidelity }: GoldenGateDesignResultsProps) {
  const selected = r.solutions.find(s => s.id === selectedSolutionId);
  return <section aria-label="Golden Gate design results"><h3>Raw design results</h3><p>Scope: {r.search_scope}. This is physical preparation/digest/ligation, not kinetics or exhaustive competing-product enumeration.</p><p>Derived geometry: {r.geometry.site}; top/bottom offsets {r.geometry.top_offset}/{r.geometry.bottom_offset}; spacer {r.geometry.spacer_length} bp; {r.geometry.overhang_length}-base {r.geometry.polarity} ends.</p><Messages values={[...r.diagnostics, ...r.limitations]} />
    {!r.solutions.length && <p>No intended product returned. Digest outcomes and diagnostics remain available.</p>}
    <label>Selected candidate<select aria-label="Selected candidate" value={selectedSolutionId ?? ''} onChange={e => onSelect(e.target.value)}><option value="">Select candidate</option>{r.solutions.map(s => <option key={s.id} value={s.id}>{s.id}: {s.sequence.length} bp, {s.topology}</option>)}</select></label>
    {selected && <section><h4>{selected.id}</h4><p>{selected.sequence.length} bp · {selected.topology} · display origin {selected.display_origin}. Exact target: {selected.exact_target_match === null ? 'not requested' : String(selected.exact_target_match)}.</p><Messages values={selected.warnings} /><textarea aria-label="Selected product DNA" readOnly value={selected.sequence} rows={4} className="w-full font-mono" /><Features features={selected.features} />{onLoadProduct && <button type="button" onClick={() => onLoadProduct(structuredClone(selected))}>Load selected product with annotations</button>}{renderSequence && <Reveal label="sequence view">{() => renderSequence(selected)}</Reveal>}
      <table><caption>Physical junctions</caption><thead><tr><th>Join</th><th>End types</th><th>Overhang</th><th>Junction DNA</th><th>Validation</th></tr></thead><tbody>{selected.junctions.map((j, i) => <tr key={i}><td>{j.left_fragment_id} → {j.right_fragment_id}</td><td>{j.left_end_type} / {j.right_end_type}</td><td>{j.overhang_sequence}</td><td>{j.junction_sequence}</td><td>{j.validation}<Messages values={j.notes} /></td></tr>)}</tbody></table>
      <h4>Residual / recreated recognition sites</h4><p>{selected.occurrences.length ? 'Product sites are present; ligatable does not mean stable or resistant to recutting.' : 'No sites reported by the native scan; activity and yield remain unmodeled.'}</p>{selected.occurrences.map(o => <p key={o.occurrence_id}>{o.canonical_name}: {o.site_start}–{o.site_end_unwrapped}, {o.orientation}, {o.certainty}{o.wraps_origin ? ', wraps origin' : ''}</p>)}
      <Reveal label="product lineage">{() => <table><caption>Actual parent mappings, not fabricated original-source slices</caption><tbody>{selected.mappings.map((m, i) => <tr key={i}><td>{m.output_start}–{m.output_end}</td><td>{m.parent_id}: {m.parent_start}–{m.parent_end}</td><td>strand {m.strand}</td></tr>)}</tbody></table>}</Reveal>
    </section>}
    <Reveal label="effective primer chemistry">{() => <table><caption>Native effective Tm settings (units in parameter names)</caption><tbody>{Object.entries(r.primer_settings).map(([key, value]) => <tr key={key}><th>{key}</th><td>{String(value)}</td></tr>)}</tbody></table>}</Reveal>
    <GoldenGateFidelityResults result={fidelity ?? null} />
    <Reveal label="primers and PCR verification">{() => <><p>Tm is on the annealing footprint; QC is on the complete oligo. Saved chemistry: {r.primer_settings.algorithm}, {r.primer_settings.salt_correction}.</p>{r.preparations.map(p => <section key={p.part_id}><h4>{p.part_id}: PCR {p.pcr_verification}</h4><p>{p.source_material_id} → {p.prepared_material_id} → {p.retained_material_id ?? 'no retained fragment'}</p><Messages values={p.pcr_diagnostics} />{p.pair_qc && <div>Pair heterodimer / 3′ complement: {p.pair_qc.heterodimer_complement} / {p.pair_qc.three_prime_heterodimer}<Messages values={p.pair_qc.warnings} /></div>}</section>)}{r.primers.map(p => <fieldset key={p.id}><legend>{p.id}: {p.part_id} {p.direction}</legend><label>Full orderable 5′→3′<textarea readOnly aria-label={`${p.id} full primer`} value={p.full_sequence} /></label><dl><dt>Clamp</dt><dd>{p.clamp || '(empty)'}</dd><dt>Recognition site / orientation</dt><dd>{p.recognition_site} / {p.recognition_orientation}</dd><dt>Spacer</dt><dd>{p.spacer}</dd><dt>Fusion</dt><dd>{p.fusion}</dd><dt>Annealing footprint</dt><dd>{p.annealing_sequence}</dd><dt>Annealing Tm (°C)</dt><dd>{p.tm.tm ?? 'unavailable'} · {p.tm.algorithm_label} · {p.tm.salt_correction_label}</dd><dt>Full-primer QC</dt><dd>Self / 3′ / hairpin: {p.qc.max_self_complement} / {p.qc.three_prime_self_complement} / {p.qc.max_hairpin_stem}; binding sites {p.qc.binding_site_count ?? 'unknown'}; off-target sites {p.qc.off_target_site_count ?? 'unknown'}; template {p.qc_template_orientation}</dd></dl><Messages values={[...p.tm.warnings, ...p.qc.warnings]} />{p.footprint_mappings.map((m, i) => <p key={i}>Footprint {m.parent_id}: {m.parent_start}–{m.parent_end}, strand {m.strand}</p>)}</fieldset>)}</>}</Reveal>
    <Reveal label="all digest outcomes and background">{() => <>{r.digests.map(d => <section key={d.part_id}><h4>{d.part_id} from {d.input_material_id}</h4><Messages values={d.warnings} />{d.fragments.map((f, i) => <fieldset key={i}><legend>Fragment {f.fragment_index} · {d.fragment_material_ids[i]}</legend><p>{d.retained_fragment_index === i ? 'Retained in intended construct' : 'Dropout / other fragment'} · {d.removed_fragment_indices.includes(i) ? 'Removed from reaction' : d.background_fragment_indices.includes(i) ? 'Reactive background remains' : 'Not listed as background'}</p><p>{f.topology}, span {f.reference_span_bp} bp; top {f.top_start_boundary}–{f.top_end_boundary}, bottom {f.bottom_start_boundary}–{f.bottom_end_boundary}{f.wraps_origin ? '; wraps origin' : ''}</p><p>Left: {f.left_end.kind} {f.left_end.protruding_strand} {f.left_end.overhang_sequence_5to3}; right: {f.right_end.kind} {f.right_end.protruding_strand} {f.right_end.overhang_sequence_5to3} (physical 5′→3′)</p><textarea aria-label={`${d.part_id} digest ${i} DNA`} readOnly value={f.top_strand_sequence} /></fieldset>)}</section>)}</>}</Reveal>
    <Reveal label="source screens and intermediates">{() => <>{r.source_screens.map(s => <section key={s.source_material_id}><h4>{s.source_material_id}</h4><Messages values={s.warnings} />{s.occurrences.map(o => <p key={o.occurrence_id}>{o.canonical_name} {o.site_start}–{o.site_end_unwrapped}: {o.orientation}, {o.certainty}{o.wraps_origin ? ', wraps' : ''}</p>)}</section>)}{r.materials.map(m => <section key={m.id}><h4>{m.id}: {m.stage} / {m.transformation}</h4><p>Parent {m.parent_id ?? 'source'} · {m.topology}</p><textarea aria-label={`${m.id} material DNA`} readOnly value={m.sequence} /><Features features={m.features} /></section>)}</>}</Reveal>
  </section>;
}
export function GoldenGateFidelityResults({ result: r }: { result: FidelityResult | null }) {
  return <section aria-label="Empirical fidelity"><h4>Estimated junction-set correctness (empirical ligation model)</h4><p>{r?.status === 'available' && r.f_set !== null ? String(r.f_set) : 'Unavailable / unscored'} · not yield or colony success; does not restrict Save.</p>{r && <><p>{r.metric_version} · {r.dataset_id ?? 'no dataset'} · {r.condition_use} · {r.scope}</p>{r.dataset && <p>Reference assay: {r.dataset.restriction_enzyme_variant} / {r.dataset.ligation_enzyme}, {r.dataset.end_length}-base ends, {r.dataset.thermal_profile}, {r.dataset.buffer}. DOI {r.dataset.doi} · {r.dataset.sha256}</p>}<Messages values={[...r.reasons, ...r.caveats]} /><p>Log set score: {r.log_f_set ?? 'unavailable'}; exact-zero observed correct event: {String(r.exact_zero_observed_correct ?? 'not reported')}.</p>{Boolean(r.pair_observations?.length) && <Reveal label="pair observations">{() => <table><caption>Reported observation counts, not kinetic constants</caption><tbody>{r.pair_observations?.map((p, i) => <tr key={i}><td>{p.a} / {p.b}</td><td>{p.observations}</td><td>{p.watson_crick ? 'Watson–Crick' : 'mispair'}</td></tr>)}</tbody></table>}</Reveal>}<p>Inventory {r.inventory_complete ? 'declared complete' : 'incomplete'}; unmodeled instances: {r.unmodeled_inventory_instance_ids.join(', ') || 'none listed'}.</p><p>Repeated classes: {r.repeated_classes?.join(', ') || 'none reported'}; palindromes: {r.palindromes?.join(', ') || 'none reported'}</p><table><caption>Per-junction estimates and joining bias (separate diagnostics)</caption><tbody>{r.per_junction?.map(j => <tr key={j.representative}><td>{j.representative} / {j.complement}</td><td>{j.probability ?? 'unavailable'}</td><td>{j.correct_observations}/{j.total_observations} observations</td><td>Relative joining bias: {r.joining_bias?.find(b => b.representative === j.representative)?.relative_to_dataset_max_pooled_wc ?? 'unknown'}</td></tr>)}</tbody></table>{r.inventory.map(end => <p key={end.instance_id}>{end.instance_id}: {end.sequence ?? 'unknown'} · {end.role} · {end.removed ? 'removed' : 'present'} · {end.phosphorylation ?? 'unknown chemistry'}</p>)}</>}</section>;
}
export function GoldenGateDomesticationResults({ result, onAccept }: { result: DomesticationResult; onAccept?: (proposal: DomesticationResult) => void }) {
  return <section aria-label="Domestication proposal"><h4>{result.status}</h4><p>{result.engine}; evaluated {result.candidates_evaluated}; search complete {String(result.search_complete)}; minimal edits proven {String(result.minimal_edits_proven)}.</p><Messages values={result.diagnostics} /><table><caption>Proposed substitutions (source unchanged)</caption><tbody>{result.edits.map(e => <tr key={e.position}><td>{e.position}</td><td>{e.original} → {e.proposed}</td><td>{e.affected_feature_ids.join(', ')}</td></tr>)}</tbody></table>{result.translations.map(t => <p key={t.feature_id}>{t.feature_id}: {t.original} → {t.proposed ?? 'no proposal'}; start {t.original_start_codon ?? 'ordinary'} → {t.proposed_start_codon ?? 'unknown'}</p>)}{result.proposed_sequence && <textarea aria-label="Proposed DNA" readOnly value={result.proposed_sequence} />}{onAccept && result.status === 'proposal' && <button type="button" onClick={() => onAccept(structuredClone(result))}>Accept this proposal as derived material</button>}<p>Acceptance must create derived lineage and recalculate primers/digest/scores. It must not relabel an edited sequence as the original immutable revision.</p></section>;
}
const rowColumns: [keyof ReactionRow, string][] = [['requested_mass_ng', 'Requested ng'], ['requested_pmol', 'Requested pmol'], ['stock_ng_per_uL', 'Stock ng/uL'], ['stock_pmol_per_uL', 'Stock pmol/uL'], ['diluted_stock_ng_per_uL', 'Diluted ng/uL'], ['diluted_stock_pmol_per_uL', 'Diluted pmol/uL'], ['exact_volume_uL', 'Exact uL'], ['transfer_volume_uL', 'Transfer uL'], ['delivered_mass_ng', 'Delivered ng'], ['delivered_pmol', 'Delivered pmol'], ['delivered_ratio_to_reference', 'Delivered ratio'], ['dilution_stock_uL', 'Dilution stock uL'], ['dilution_diluent_uL', 'Dilution diluent uL'], ['batch_volume_uL', 'Batch uL'], ['mastermix_volume_uL', 'Mastermix uL']];
export function GoldenGateReactionResults({ result: r }: { result: ReactionResult }) {
  return <section aria-label="Reaction worksheet"><h4>Reaction worksheet</h4><p>{r.mass_basis_description} Basis {r.request.settings.mass_basis_g_per_mol_bp} g/mol/bp.</p><p>Known subtotal: {r.known_transfer_subtotal_uL} uL; full total: {r.total_transfer_uL ?? 'unknown'} uL; exact water: {r.water_exact_uL ?? 'unknown'} uL; mastermix total: {r.mastermix_total_uL ?? 'unknown'} uL.</p><Messages values={r.diagnostics.map(d => `${d.component_id ?? 'reaction'}: ${d.code} — ${d.message}`)} /><div className="overflow-x-auto"><table><thead><tr><th>Component</th>{rowColumns.map(([key, label]) => <th key={key}>{label}</th>)}</tr></thead><tbody>{r.rows.map(row => <tr key={row.component_id}><th>{row.component_id}</th>{rowColumns.map(([key]) => <td key={key}>{row[key] ?? 'unknown'}</td>)}</tr>)}</tbody></table></div></section>;
}
