import { useEffect, useRef, useState } from 'react';
import { useInfiniteQuery, useQuery, useQueryClient } from '@tanstack/react-query';
import { fetchGoldenGateAssemblyOptions, fetchUserTemplates, createUserTemplate, fetchUserTemplate, fetchPrimerTmOptions, fetchSavedGibsonWorkups, fetchNucleotideSequence, type GoldenGateAssemblyOptionsResponse } from '../../../../lib/api';
import { designGoldenGate, saveGoldenGateDesign, readGoldenGateDesign, exportGoldenGateDesign, importGoldenGateDesign, freezeGoldenGateSelection, cloneGoldenGateRequest } from '../../../../lib/goldenGateWorkflow';
import type { SavedDesign, WorkflowRequest, WorkflowResult } from '../../../../lib/goldenGateWorkflowTypes';
import { reusableDigestChoices } from '../../../../lib/goldenGateDesign';
import type { GoldenGateDesignRequest, Solution, FidelityResult, SearchResult, SourceChoice, GoldenGateDesignResult } from '../../../../lib/goldenGateDesign';
import { thermodynamicsDefaults } from '../../../../lib/goldenGateWorkflowDefaults';
import type { SequenceData } from '../../types';
import { SequenceViewer } from '../../SequenceViewer';
import { DEFAULT_VISIBILITY } from '../../sequenceViewerConstants';
import { GoldenGateWorkflowControls, initialWorkflow } from './GoldenGateWorkflowControls';
import { GoldenGateDesignResults, GoldenGateFidelityResults, GoldenGateReactionResults, GoldenGateDomesticationResults } from './GoldenGateDesignResults';
import { GoldenGateSearchResults } from './GoldenGateSearchResults';
import { Choice, Text } from './Fields';
import { GoldenGateBatchPanel } from './GoldenGateBatchPanel';
import type { BatchSlot, BatchScope, BatchRequest } from '../../../../lib/goldenGateBatch';

export function workflowProduct(product: Solution, design: GoldenGateDesignResult, name: string): SequenceData {
 const features = product.features.map(f => ({...f,start:f.segments[0]?.start ?? 0,end:f.segments.at(-1)?.end ?? 0,strand:(f.strand === -1 ? -1 : 1) as 1|-1,qualifiers:{...f.qualifiers,bms_strand:f.strand,codon_start:f.codon_start,bms_status:f.status,bms_frame_preserved:f.frame_preserved}}));
 return {name,sequence:product.sequence,circular:product.topology === 'circular',sequenceType:'dna',features,
 primers:design.primers.flatMap(p => { const f=features.find(f => f.id === `${p.part_id}:${p.id}:binding` || f.id === `${p.id}:binding`); return f ? [{id:p.id,name:p.id,sequence:p.full_sequence,start:f.start,end:f.end,strand:f.strand,tm:p.tm.tm ?? undefined,tm_settings:design.primer_settings,notes:{annealing_sequence:p.annealing_sequence,footprint_mappings:p.footprint_mappings}}] : []; })};
}
export default function GoldenGateWorkflowWorkspace({ sequenceData, options: suppliedOptions, onLoadProduct, operationId }: {
 sequenceData: SequenceData; options: GoldenGateAssemblyOptionsResponse | null; onLoadProduct: (v: SequenceData, id?: string | null) => void; operationId?: string;
}) {
 const discovery=useQuery({queryKey:['molbio-golden-gate-options'],queryFn:async({signal})=>(await fetchGoldenGateAssemblyOptions(signal)).data,enabled:!suppliedOptions,staleTime:300000});
 const options=suppliedOptions ?? discovery.data ?? null;
 const source: SourceChoice = {label:`Editor snapshot: ${sequenceData.name}`,source:{id:'source',source:{kind:'inline',sequence:sequenceData.sequence,topology:sequenceData.circular ? 'circular' : 'linear',features:sequenceData.features.map(f => ({id:f.id,name:f.name,type:f.type,segments:(f.segments ?? [{start:f.start,end:f.end}]).map(s => ({...s,wraps_origin:s.start>s.end})),strand:f.strand,qualifiers:f.qualifiers ?? f.notes ?? {},codon_start:(f.qualifiers?.codon_start as 1|2|3) ?? null,status:'intact',frame_preserved:null}))}}};
 const enzymes = options?.catalog ? options.enzymes.filter(e => !options.raw_design || options.raw_design.raw_enzyme_adapters.includes(e.canonical_name)).map(e => ({enzyme_id:e.enzyme_id,...options.catalog!})) : [];
 const core: GoldenGateDesignRequest = {schema_version:'bms.golden-gate-design.v1',task:'assemble_parts',sources:[source.source],parts:[],target:{topology:'circular',display_origin:0,exact_sequence:null},enzyme:{enzyme_id:'',catalog_id:'',catalog_sha256:''},primer_settings:{...thermodynamicsDefaults}};
 const [draft,setDraft] = useState<WorkflowRequest>(() => initialWorkflow('assemble_parts',core));
 const [receipt,setReceipt] = useState<{owner: WorkflowRequest; result:WorkflowResult; saved?:SavedDesign; frozen:boolean} | null>(null);
 const [selected,setSelected] = useState<string | null>(null); const [name,setName]=useState('Golden Gate design'); const [description,setDescription]=useState('');
 const [presetsOpen,setPresetsOpen]=useState(false);
 const [batchSlots,setBatchSlots]=useState<BatchSlot[]>([]); const [batchScope,setBatchScope]=useState<BatchScope>({mode:'full'});
 const configuration: WorkflowRequest | BatchRequest = draft.task === 'assemble_parts' && batchSlots.length ? {schema_version:'bms.golden-gate-batch.v1',base:draft,slots:batchSlots,scope:batchScope} : draft;
 const presets=useQuery({queryKey:['user-templates','golden_gate_design'],queryFn:async()=>(await fetchUserTemplates(undefined,undefined,'golden_gate_design')).data,enabled:presetsOpen,staleTime:300000});
 const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false); const [shelf,setShelf]=useState(false);
 const current=useRef(draft); current.current=draft; const active=useRef<AbortController|null>(null); const generation=useRef(0); const selectedRef=useRef(selected); selectedRef.current=selected;
 // A Save acknowledgement replaces the receipt wrapper, not the result or save intent.
 const saveKey=useRef<{result:WorkflowResult;selected:string;name:string;description:string;key:string}|null>(null);
 const qc=useQueryClient();
 const tm=useQuery({queryKey:['molbio-primer-tm-options'],queryFn:async({signal})=>(await fetchPrimerTmOptions(signal)).data,staleTime:300000});
 const workups=useInfiniteQuery({queryKey:['molbio-saved-gibson-workups'],queryFn:async({pageParam,signal})=>(await fetchSavedGibsonWorkups({limit:50,offset:pageParam},signal)).data,initialPageParam:0,getNextPageParam:(p,ps)=>p.length===50?ps.reduce((n,p)=>n+p.length,0):undefined,enabled:shelf,staleTime:Infinity,gcTime:1800000});
 const visible=receipt?.owner===draft?receipt:null;
 const result=visible?.result; const candidate=result?.solutions.find(s=>s.id===selected);
 const reaction=candidate?.reaction !== undefined ? candidate.reaction : (selected===result?.selected_solution_id ? result?.reaction : null);
 const edit=(v:WorkflowRequest)=>{active.current?.abort();generation.current++;setBusy(false);current.current=v;setDraft(v);setMessage('');};
 useEffect(()=>()=>{active.current?.abort();generation.current++;},[]);
 const receive=(r:WorkflowResult,saved?:SavedDesign)=>{const request=structuredClone(r.requested);current.current=request;setDraft(request);setReceipt({owner:request,result:r,saved,frozen:true});setSelected(r.selected_solution_id);};
 useEffect(()=>{if(!operationId)return;const controller=new AbortController();const g=++generation.current;active.current?.abort();active.current=controller;void readGoldenGateDesign(operationId,controller.signal).then(({data})=>{if(g===generation.current&&!controller.signal.aborted)receive(data.result,data);}).catch(e=>{if(!controller.signal.aborted)setMessage(String(e));});return()=>controller.abort();},[operationId]);
 const run=async()=>{active.current?.abort();const controller=new AbortController();active.current=controller;const owner=draft;const g=++generation.current;setBusy(true);setReceipt(null);setMessage('');try{const {data}=await designGoldenGate(structuredClone(owner),controller.signal);if(current.current===owner&&g===generation.current&&!controller.signal.aborted){setReceipt({owner,result:data,frozen:false});setSelected(data.selected_solution_id);}}catch(e){if(g===generation.current&&!controller.signal.aborted)setMessage(String(e));}finally{if(g===generation.current)setBusy(false);}};
 const save=async()=>{if(!visible||!selected)return;const owner=draft;const sel=selected;const g=generation.current;
 if(!saveKey.current||saveKey.current.result!==visible.result||saveKey.current.selected!==sel||saveKey.current.name!==name||saveKey.current.description!==description)saveKey.current={result:visible.result,selected:sel,name,description,key:crypto.randomUUID()};
 try{const {data}=await saveGoldenGateDesign({schema_version:'bms.golden-gate-save.v1',selection:freezeGoldenGateSelection(visible.result,sel),name,description:description||null,idempotency_key:saveKey.current.key});void qc.invalidateQueries({queryKey:['molbio-saved-gibson-workups']});if(current.current===owner&&selectedRef.current===sel&&g===generation.current){setReceipt({...visible,saved:data});setMessage(`Saved operation ${data.operation_id}`);}}catch(e){if(current.current===owner&&g===generation.current)setMessage(String(e));}};
 const open=async(id:string)=>{const g=++generation.current;active.current?.abort();const controller=new AbortController();active.current=controller;try{const seq=(await fetchNucleotideSequence(id)).data;const op=seq.operation_params?.operation_id;if(typeof op!=='string')throw new Error('This workup uses the historical Assembly viewer.');const {data}=await readGoldenGateDesign(op,controller.signal);if(g===generation.current)receive(data.result,data);}catch(e){if(g===generation.current)setMessage(String(e));}};
 const download=async()=>{if(!result)return;const displayed={...result,selected_solution_id:selected};try{const saved=visible?.saved;const {data}=await exportGoldenGateDesign(displayed,saved?.selection.solution_id===selected?saved.operation_id:undefined);const url=URL.createObjectURL(data);const a=document.createElement('a');a.href=url;a.download='golden-gate.zip';a.click();URL.revokeObjectURL(url);}catch(e){setMessage(String(e));}};
 const load=(p:Solution)=>{if(!candidate)return;const data=workflowProduct(p,candidate.design,name);const saved=visible?.saved?.selection.solution_id===selected?visible.saved:undefined;if(saved){data.operation='golden_gate_design';data.operationParams={operation_id:saved.operation_id};}onLoadProduct(data,saved?.product_document_id);};
 return <section aria-label="Golden Gate native workflow" className="space-y-4">
 <details onToggle={e=>setPresetsOpen(e.currentTarget.open)}><summary>User-defined standards / saved configurations</summary><p>A named configuration retains this versioned request, exact slots, enzyme and scientific settings. Loading is explicit; it does not run science or apply a shipped standard.</p><Text label="Configuration name" value={name} onChange={v=>{generation.current++;setName(v);}}/><button onClick={async()=>{try{const {data}=await createUserTemplate({name,description,icon:'bookmark',color:'#6B7280',base_template_id:null,model_id:null,mode:'golden_gate_design',params:structuredClone(configuration)});const read=(await fetchUserTemplate(data.id)).data;if(JSON.stringify(read.params)!==JSON.stringify(configuration))throw new Error('Saved configuration differs; inspect retained settings.');void qc.invalidateQueries({queryKey:['user-templates','golden_gate_design']});setMessage(`Saved configuration ${read.name}`);}catch(e){setMessage(String(e));}}}>Save named configuration</button>{presets.data?.map(p=><button key={p.id} onClick={async()=>{try{const {data}=await fetchUserTemplate(p.id);if(data.mode!=='golden_gate_design')throw new Error('Unsupported configuration mode');if(data.params.schema_version==='bms.golden-gate-batch.v1'){const batch=structuredClone(data.params) as BatchRequest;setBatchSlots(batch.slots);setBatchScope(batch.scope);edit(batch.base);}else if(data.params.schema_version==='bms.golden-gate-design.v1'){setBatchSlots([]);edit(structuredClone(data.params) as WorkflowRequest);}else throw new Error('Unsupported configuration version');}catch(e){setMessage(String(e));}}}>Load configuration {p.name}</button>)}</details>
 <h3>Golden Gate design and workup</h3><p>Local planning. No automatic DNA edits, third-party uploads or design on field changes.</p>
 <button onClick={()=>setShelf(!shelf)}>Saved Golden Gate workups{workups.data?` (${workups.data.pages.flat().length} assembly records loaded)`:' (not loaded)'}</button>{shelf&&<div><button onClick={()=>void workups.refetch()}>Refresh workups</button>{workups.data?.pages.flat().map(w=><div key={w.id}>{w.name} · {w.engine}<button onClick={()=>void open(w.id)}>Open {w.name}</button></div>)}{workups.hasNextPage&&<button onClick={()=>void workups.fetchNextPage()}>Load more workups</button>}{workups.error&&<p>{String(workups.error)}</p>}</div>}
 <label>Import frozen workflow.json<input aria-label="Import frozen workflow.json" type="file" accept=".json,application/json" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;const g=++generation.current;active.current?.abort();try{const document=JSON.parse(await file.text());const {data}=await importGoldenGateDesign(document);if(g===generation.current)receive(data);}catch(error){if(g===generation.current)setMessage(String(error));}}}/></label>
 <fieldset disabled={visible?.frozen}><Choice label="Golden Gate task" value={draft.task} values={['assemble_parts','split_target','evaluate_overhangs','optimize_overhangs']} onChange={task=>edit(initialWorkflow(task,draft.task==='assemble_parts'?draft:core))}/><GoldenGateWorkflowControls value={draft} onChange={edit} digests={receipt?.result.requested.task === 'assemble_parts' && draft.task === 'assemble_parts' ? reusableDigestChoices(receipt.result.requested,draft,receipt.result.solutions.find(s=>s.id===selected)?.design.digests ?? []) : []} sourceChoices={[source]} enzymes={enzymes} datasets={(options?.raw_design?.datasets??[]).map(d=>({id:d.id,label:d.id,description:`${d.restriction_enzyme_variant} · ${d.thermal_profile} · ${d.buffer}`}))} tmOptions={tm.data??null}/></fieldset>
 {visible?.frozen?<button onClick={()=>{const request=cloneGoldenGateRequest({...visible.result,selected_solution_id:selected});edit(request);setReceipt(null);}}>Clone retained settings into editable design</button>:<><button onClick={()=>void run()}>{busy?'Restart Golden Gate design':'Run Golden Gate task'}</button>{busy&&<button onClick={()=>{active.current?.abort();generation.current++;setBusy(false);}}>Cancel preview</button>}</>}
 {draft.task==='assemble_parts'&&<GoldenGateBatchPanel base={draft} slots={batchSlots} scope={batchScope} onSlots={setBatchSlots} onScope={setBatchScope} onEdit={edit} onResult={r=>{active.current?.abort();generation.current++;setBusy(false);receive(r);}}/>}
 {message&&<p role="status">{message}</p>}
 {result&&<><ul>{result.diagnostics.map((d,i)=><li key={i}>{d}</li>)}</ul>{result.evaluation&&<GoldenGateFidelityResults result={result.evaluation as unknown as FidelityResult}/>} {result.search_result&&<GoldenGateSearchResults result={result.search_result as unknown as SearchResult} selectedIndex={null} onSelect={(_i,s)=>{if(draft.task==='optimize_overhangs')edit({...initialWorkflow('evaluate_overhangs',core),task:'evaluate_overhangs',fidelity:draft.fidelity,junctions:s.junctions,inventory:[],inventory_complete:false});}}/>}
 {result.solutions.length>0&&<Choice label="Selected workflow candidate" value={selected??''} values={result.solutions.map(s=>s.id)} onChange={v=>{generation.current++;selectedRef.current=v;setSelected(v);setMessage('');}}/>}
 {candidate&&<GoldenGateDesignResults result={candidate.design} selectedSolutionId={candidate.design.selected_solution_id} onSelect={()=>{}} fidelity={candidate.fidelity as unknown as FidelityResult} onLoadProduct={load} renderSequence={p=><SequenceViewer sequenceData={workflowProduct(p,candidate.design,name)} visibility={DEFAULT_VISIBILITY}/>}/>}
 {result.edits.map(e=><GoldenGateDomesticationResults key={e.source_id} result={e.proposal} onAccept={!visible?.frozen&&draft.task==='assemble_parts'?proposal=>edit({...draft,domestication:draft.domestication.map(x=>x.source_id===e.source_id?{...x,accepted_sequence:proposal.proposed_sequence}:x)}):undefined}/>)}
 {reaction&&<GoldenGateReactionResults result={reaction}/>}
 <Text label="Workup name" value={name} onChange={v=>{generation.current++;setName(v);}}/><Text label="Workup description" value={description} onChange={v=>{generation.current++;setDescription(v);}}/>{candidate&&<button onClick={()=>void save()}>Save fixed selected candidate</button>}
 <button onClick={()=>void download()}>Export frozen workup ZIP</button>{visible?.saved&&<button onClick={()=>{const id=visible.saved!.operation_id;const g=++generation.current;void readGoldenGateDesign(id).then(({data})=>{if(g===generation.current)receive(data.result,data);}).catch(e=>{if(g===generation.current)setMessage(String(e));});}}>Reopen retained workup</button>}
 <details><summary>Compare externally (copy only)</summary><p>No sequence is uploaded. Empirical reference is not yield.</p><textarea readOnly aria-label="External comparison" value={candidate?candidate.design.solutions.flatMap(s=>s.junctions.map(j=>j.overhang_sequence??'')).join(' '):JSON.stringify(result.evaluation??result.search_result)}/></details>
 </>}
 {visible?.saved&&<button onClick={()=>{const saved=visible.saved!;const request=initialWorkflow('assemble_parts',{...core,sources:[{id:'previous-stage-product',source:{kind:'molecular_revision',revision_id:saved.product_revision_id}}],enzyme:candidate?.fixed_request.enzyme??core.enzyme,primer_settings:candidate?.fixed_request.primer_settings??core.primer_settings});edit(request);setBatchSlots([]);setReceipt(null);setMessage('Next stage uses the saved immutable product revision. Select its preparation and this stage’s enzyme/settings independently; the previous stage is unchanged.');}}>Start next stage from saved immutable product</button>}
 <p>Repeated stages use saved immutable product revisions. Named configurations retain exact user settings and any authored batch slots; loading never executes science.</p>
 </section>;
}
