from __future__ import annotations

import copy
import hashlib
import json
import math
import os
import re
import stat
import tempfile
from collections.abc import Callable, Mapping
from functools import lru_cache
from pathlib import Path
from typing import Any

from jsonschema import Draft202012Validator
from jsonschema.exceptions import SchemaError

from scripts.bms_md.contract import normalize_job_config
from services.md.chemistry_catalog import (
    CatalogView,
    ChemistryCatalog,
    ChemistryProfileSelectionError,
    get_chemistry_catalog,
)

MAX_MD_STRUCTURE_BYTES = 100 * 1024 * 1024
HASH_CHUNK_BYTES = 1024 * 1024
PROFILE_CLAIM_FIELDS = (
    "chemistry_profile_id",
    "chemistry_profile_sha256",
    "chemistry_profile_scope",
)
GENERATED_INPUT_DIGEST_FIELDS = (
    "structure_sha256",
    "coordinates_sha256",
    "topology_sha256",
)
MD_JOB_SCHEMA_PATH = Path(__file__).resolve().parents[4] / "schemas" / "md_job_v1.schema.json"


class MDLaunchError(ValueError):
    """Stable, client-safe failure raised by the MD launch boundary."""

    def __init__(self, code: str, message: str, *, status_code: int) -> None:
        self.code = code
        self.status_code = status_code
        super().__init__(message)


@lru_cache(maxsize=1)
def _md_job_validator() -> Draft202012Validator:
    schema = json.loads(MD_JOB_SCHEMA_PATH.read_text(encoding="utf-8"))
    Draft202012Validator.check_schema(schema)
    return Draft202012Validator(schema)


def _validate_raw_input_semantics(candidate: Mapping[str, Any]) -> None:
    input_config = candidate.get("input")
    if not isinstance(input_config, Mapping):
        return
    claimed_digests = [field for field in GENERATED_INPUT_DIGEST_FIELDS if field in input_config]
    if claimed_digests:
        raise MDLaunchError(
            "MD_INPUT_DIGEST_FORBIDDEN",
            "Molecular-dynamics input digests are generated by the server during materialization.",
            status_code=422,
        )
    has_structure = bool(str(input_config.get("structure") or "").strip())
    has_coordinates = bool(str(input_config.get("coordinates") or "").strip())
    has_topology = bool(str(input_config.get("topology") or "").strip())
    if has_structure and (has_coordinates or has_topology):
        raise ValueError("MD input must use exactly one input mode: structure or prepared coordinates plus topology")
    if not has_structure and not (has_coordinates and has_topology):
        raise ValueError("input requires structure or coordinates plus topology")
    if has_structure:
        return
    preparation = candidate.get("preparation")
    if not isinstance(preparation, Mapping):
        return
    attached_claims = [field for field in PROFILE_CLAIM_FIELDS if field in preparation]
    if attached_claims:
        raise ChemistryProfileSelectionError(
            "MD_CHEMISTRY_PROFILE_FORBIDDEN",
            "Prepared external systems cannot carry v1 chemistry profile claims: "
            f"{', '.join(attached_claims)}.",
        )


def _resource_violation(field: str) -> MDLaunchError:
    return MDLaunchError(
        "MD_RESOURCE_CONTRACT_VIOLATION",
        f"The molecular-dynamics resource contract is invalid at {field}.",
        status_code=422,
    )


def _bounded_resource_int(value: Any, field: str, *, minimum: int, maximum: int) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or not minimum <= value <= maximum:
        raise _resource_violation(field)
    return value


def _bounded_resource_number(
    value: Any,
    field: str,
    *,
    maximum: float,
    minimum: float = 0.0,
) -> float:
    if (
        isinstance(value, bool)
        or not isinstance(value, (int, float))
        or not math.isfinite(float(value))
        or float(value) <= 0
        or float(value) < minimum
        or float(value) > maximum
    ):
        raise _resource_violation(field)
    return float(value)


def _validate_resource_contract(candidate: Mapping[str, Any]) -> None:
    if "replicas" not in candidate:
        return
    replicas = _bounded_resource_int(candidate.get("replicas"), "replicas", minimum=1, maximum=8)
    stages = candidate.get("stages")
    execution = candidate.get("execution")
    if not isinstance(stages, Mapping):
        raise _resource_violation("stages")
    if not isinstance(execution, Mapping):
        raise _resource_violation("execution")

    step_limits = {
        "minimization": 5_000_000,
        "nvt": 5_000_000,
        "npt": 5_000_000,
        "production": 50_000_000,
    }
    enabled_steps = 0
    normalized_steps: dict[str, int] = {}
    for stage_name, maximum in step_limits.items():
        stage = stages.get(stage_name)
        if not isinstance(stage, Mapping):
            raise _resource_violation(f"stages.{stage_name}")
        steps = _bounded_resource_int(
            stage.get("steps"),
            f"stages.{stage_name}.steps",
            minimum=1,
            maximum=maximum,
        )
        normalized_steps[stage_name] = steps
        if stage.get("enabled") is True:
            enabled_steps += steps

    production = stages["production"]
    _bounded_resource_number(
        production.get("timestep_fs"),
        "stages.production.timestep_fs",
        maximum=4.0,
    )
    _bounded_resource_number(
        production.get("checkpoint_interval_minutes"),
        "stages.production.checkpoint_interval_minutes",
        minimum=1.0,
        maximum=1440.0,
    )
    output_intervals: dict[str, int] = {}
    for field in ("trajectory_interval_steps", "energy_interval_steps"):
        interval = _bounded_resource_int(
            production.get(field),
            f"stages.production.{field}",
            minimum=1,
            maximum=50_000_000,
        )
        if interval > normalized_steps["production"]:
            raise _resource_violation(f"stages.production.{field}")
        output_intervals[field] = interval

    production_steps = normalized_steps["production"]
    trajectory_records = replicas * (
        (production_steps + output_intervals["trajectory_interval_steps"] - 1)
        // output_intervals["trajectory_interval_steps"]
    )
    if trajectory_records > 1_000_000:
        raise _resource_violation("aggregate_trajectory_records")
    energy_records = replicas * (
        (production_steps + output_intervals["energy_interval_steps"] - 1)
        // output_intervals["energy_interval_steps"]
    )
    if energy_records > 5_000_000:
        raise _resource_violation("aggregate_energy_records")

    _bounded_resource_int(execution.get("ntmpi"), "execution.ntmpi", minimum=1, maximum=1)
    _bounded_resource_int(execution.get("ntomp"), "execution.ntomp", minimum=1, maximum=128)
    if enabled_steps * replicas > 500_000_000:
        raise _resource_violation("aggregate_enabled_stage_steps")


def _validate_raw_md_job_spec(candidate: Mapping[str, Any]) -> None:
    try:
        errors = sorted(
            _md_job_validator().iter_errors(candidate),
            key=lambda error: tuple(str(part) for part in error.absolute_path),
        )
    except (OSError, json.JSONDecodeError, SchemaError) as exc:
        raise MDLaunchError(
            "MD_LAUNCH_SERVICE_UNAVAILABLE",
            "The molecular-dynamics launch contract is temporarily unavailable.",
            status_code=503,
        ) from exc
    if not errors:
        return
    raise MDLaunchError(
        "MD_JOB_CONTRACT_INVALID",
        "The molecular-dynamics job contract is invalid.",
        status_code=422,
    )


def _scope_violation(field: str, message: str) -> ChemistryProfileSelectionError:
    return ChemistryProfileSelectionError(
        "MD_CHEMISTRY_SCOPE_VIOLATION",
        f"Chemistry launch scope violation for {field}: {message}",
    )


def sha256_file_bounded(path: Path, *, max_bytes: int = MAX_MD_STRUCTURE_BYTES) -> str:
    size = path.stat().st_size
    if size > max_bytes:
        raise _scope_violation("input.structure", "structure exceeds the 100 MiB hashing limit")
    digest = hashlib.sha256()
    consumed = 0
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(HASH_CHUNK_BYTES), b""):
            consumed += len(chunk)
            if consumed > max_bytes:
                raise _scope_violation("input.structure", "structure exceeds the 100 MiB hashing limit")
            digest.update(chunk)
    return digest.hexdigest()


def _safe_snapshot_suffix(path: Path) -> str:
    suffix = path.suffix.lower()
    return suffix if re.fullmatch(r"\.[a-z0-9]{1,10}", suffix) else ".bin"


def _fsync_directory(path: Path) -> None:
    descriptor = os.open(path, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
    try:
        os.fsync(descriptor)
    finally:
        os.close(descriptor)


def _snapshot_input_file(
    *,
    source: Path,
    field: str,
    contract_dir: Path,
    expected_sha256: str | None = None,
) -> tuple[Path, str]:
    destination = contract_dir / f"{field}{_safe_snapshot_suffix(source)}"
    descriptor, temporary_name = tempfile.mkstemp(prefix=f".{field}.", suffix=".tmp", dir=contract_dir)
    temporary = Path(temporary_name)
    digest = hashlib.sha256()
    consumed = 0
    published = False
    try:
        with os.fdopen(descriptor, "wb") as snapshot_handle:
            try:
                source_handle = source.open("rb")
            except FileNotFoundError as exc:
                raise MDLaunchError(
                    "MD_INPUT_MISSING",
                    "A molecular-dynamics input disappeared before it could be snapshotted.",
                    status_code=409,
                ) from exc
            with source_handle:
                source_stat = os.fstat(source_handle.fileno())
                if not stat.S_ISREG(source_stat.st_mode):
                    raise MDLaunchError(
                        "MD_INPUT_MISSING",
                        "A molecular-dynamics input is no longer an available regular file.",
                        status_code=409,
                    )
                if source_stat.st_size > MAX_MD_STRUCTURE_BYTES:
                    raise MDLaunchError(
                        "MD_INPUT_TOO_LARGE",
                        "A molecular-dynamics input exceeds the bounded snapshot limit.",
                        status_code=422,
                    )
                for chunk in iter(lambda: source_handle.read(HASH_CHUNK_BYTES), b""):
                    consumed += len(chunk)
                    if consumed > MAX_MD_STRUCTURE_BYTES:
                        raise MDLaunchError(
                            "MD_INPUT_TOO_LARGE",
                            "A molecular-dynamics input exceeds the bounded snapshot limit.",
                            status_code=422,
                        )
                    snapshot_handle.write(chunk)
                    digest.update(chunk)
            snapshot_handle.flush()
            os.fsync(snapshot_handle.fileno())
        actual_sha256 = digest.hexdigest()
        if expected_sha256 is not None and actual_sha256 != expected_sha256:
            raise _scope_violation(
                "structure_sha256",
                "the copied structure bytes do not match the authorized smoke fixture",
            )
        os.chmod(temporary, 0o444)
        try:
            os.link(temporary, destination)
        except FileExistsError as exc:
            raise MDLaunchError(
                "MD_LAUNCH_OUTPUT_CONFLICT",
                "The molecular-dynamics launch output already contains an authoritative input snapshot.",
                status_code=409,
            ) from exc
        published = True
        temporary.unlink()
        _fsync_directory(contract_dir)
        return destination.resolve(), actual_sha256
    except Exception:
        temporary.unlink(missing_ok=True)
        if published:
            destination.unlink(missing_ok=True)
        raise


def _atomic_write_contract(path: Path, payload: Mapping[str, Any]) -> None:
    descriptor, temporary_name = tempfile.mkstemp(prefix=".md_job_config.", suffix=".tmp", dir=path.parent)
    temporary = Path(temporary_name)
    published = False
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        try:
            os.link(temporary, path)
        except FileExistsError as exc:
            raise MDLaunchError(
                "MD_LAUNCH_OUTPUT_CONFLICT",
                "The molecular-dynamics launch output already contains an authoritative contract.",
                status_code=409,
            ) from exc
        published = True
        temporary.unlink()
        _fsync_directory(path.parent)
    except Exception:
        temporary.unlink(missing_ok=True)
        if published:
            path.unlink(missing_ok=True)
        raise


def _validate_profile_launch_constraints(normalized: Mapping[str, Any], profile: Mapping[str, Any]) -> None:
    constraints = profile.get("launch_constraints")
    if not isinstance(constraints, Mapping):
        raise _scope_violation("launch_constraints", "selected profile has no valid launch constraints")
    preparation = normalized["preparation"]
    stages = normalized["stages"]
    structure = Path(str(normalized["input"]["structure"]))

    exact_values = (
        ("input_mode", "structure", constraints["input_mode"]),
        ("replicas", normalized["replicas"], constraints["replicas"]),
        ("engine", normalized["engine"], constraints["engine"]),
        ("force_field", preparation.get("force_field"), constraints["force_field"]),
        ("water_model", preparation.get("water_model"), constraints["water_model"]),
        ("salt_molar", preparation.get("salt_molar"), constraints["salt_molar"]),
        ("padding_nm", preparation.get("padding_nm"), constraints["padding_nm"]),
        ("timestep_fs", stages["production"].get("timestep_fs"), constraints["timestep_fs"]),
    )
    for field, actual, expected in exact_values:
        if actual != expected:
            raise _scope_violation(field, f"expected {expected!r}, received {actual!r}")

    for stage_name in ("nvt", "npt", "production"):
        actual = stages[stage_name].get("temperature_k")
        if actual != constraints["temperature_k"]:
            raise _scope_violation(
                "temperature_k",
                f"{stage_name} expected {constraints['temperature_k']!r}, received {actual!r}",
            )
    for stage_name in ("npt", "production"):
        actual = stages[stage_name].get("pressure_bar")
        if actual != constraints["pressure_bar"]:
            raise _scope_violation(
                "pressure_bar",
                f"{stage_name} expected {constraints['pressure_bar']!r}, received {actual!r}",
            )

    maximums = {
        "minimization": constraints["max_minimization_steps"],
        "nvt": constraints["max_nvt_steps"],
        "npt": constraints["max_npt_steps"],
        "production": constraints["max_production_steps"],
    }
    for stage_name, maximum in maximums.items():
        actual = stages[stage_name].get("steps")
        if not isinstance(actual, int) or actual > maximum:
            raise _scope_violation(f"{stage_name}.steps", f"maximum is {maximum}, received {actual!r}")

    actual_digest = sha256_file_bounded(structure)
    if actual_digest != constraints["structure_sha256"]:
        raise _scope_violation(
            "structure_sha256",
            f"expected authorized structure {constraints['structure_sha256']}, received {actual_digest}",
        )


def normalize_md_job_spec(
    *,
    params: Mapping[str, Any],
    job_id: str,
    resolve_runtime_path: Callable[[str], str],
    chemistry_catalog: ChemistryCatalog | None = None,
    chemistry_view: CatalogView | None = None,
) -> dict[str, Any]:
    """Validate a structured MD launch request without performing I/O."""

    spec = params.get("md_job_spec")
    if not isinstance(spec, Mapping):
        raise ValueError("md_job_spec must be an object")

    candidate = copy.deepcopy(dict(spec))
    candidate["job_id"] = job_id
    _validate_raw_input_semantics(candidate)
    _validate_resource_contract(candidate)
    _validate_raw_md_job_spec(candidate)
    input_config = candidate.get("input")
    if isinstance(input_config, Mapping):
        normalized_input = dict(input_config)
        for field in ("structure", "coordinates", "topology"):
            value = normalized_input.get(field)
            if isinstance(value, str) and value.strip():
                normalized_input[field] = resolve_runtime_path(value.strip())
        candidate["input"] = normalized_input

    normalized = normalize_job_config(candidate)
    has_structure = bool(normalized["input"].get("structure"))
    has_prepared = bool(normalized["input"].get("coordinates")) or bool(normalized["input"].get("topology"))
    if has_structure and has_prepared:
        raise ValueError("MD input must use exactly one input mode: structure or prepared coordinates plus topology")
    if normalized["engine"] == "openmm" and any(
        normalized["stages"][stage]["enabled"] for stage in ("minimization", "nvt", "npt")
    ):
        raise ValueError("OpenMM is production-only; disable minimization, nvt, and npt")

    for field in ("structure", "coordinates", "topology"):
        value = normalized["input"].get(field)
        if value and not Path(str(value)).is_file():
            raise MDLaunchError(
                "MD_INPUT_MISSING",
                "A molecular-dynamics input is missing or is no longer a regular file.",
                status_code=409,
            )

    preparation = dict(normalized["preparation"])
    if has_structure:
        catalog = chemistry_catalog or get_chemistry_catalog()
        captured_view = chemistry_view or catalog.view()
        profile = catalog.validate_v1_profile_selection(
            profile_id=preparation.get("chemistry_profile_id"),
            profile_sha256=preparation.get("chemistry_profile_sha256"),
            force_field=str(preparation.get("force_field") or ""),
            water_model=str(preparation.get("water_model") or ""),
            engine=normalized["engine"],
            requested_scope=preparation.get("chemistry_profile_scope"),
            view=captured_view,
        )
        if preparation.get("chemistry_assurance") != profile["assurance"]:
            raise ChemistryProfileSelectionError(
                "MD_CHEMISTRY_PROFILE_UNAVAILABLE",
                f"Chemistry profile {profile['id']} requires assurance {profile['assurance']}.",
            )
        normalized["preparation"] = preparation
        _validate_profile_launch_constraints(normalized, profile)
    else:
        attached_claims = [field for field in PROFILE_CLAIM_FIELDS if field in preparation]
        if attached_claims:
            raise ChemistryProfileSelectionError(
                "MD_CHEMISTRY_PROFILE_FORBIDDEN",
                "Prepared external systems cannot carry v1 chemistry profile claims: "
                f"{', '.join(attached_claims)}.",
            )
        if preparation.get("chemistry_assurance") != "external_unreviewed":
            raise ChemistryProfileSelectionError(
                "MD_CHEMISTRY_PROFILE_REQUIRED",
                "Prepared external systems must declare chemistry_assurance=external_unreviewed.",
            )
        normalized["preparation"] = preparation
    return normalized


def materialize_md_job_spec(
    *,
    params: Mapping[str, Any],
    job_id: str,
    output_dir: Path,
    resolve_runtime_path: Callable[[str], str],
    chemistry_catalog: ChemistryCatalog | None = None,
) -> dict[str, Any]:
    """Validate and persist the authoritative MD contract for a parent job."""

    raw_spec = params.get("md_job_spec")
    raw_input = raw_spec.get("input") if isinstance(raw_spec, Mapping) else None
    has_structure = isinstance(raw_input, Mapping) and bool(str(raw_input.get("structure") or "").strip())
    catalog = chemistry_catalog or get_chemistry_catalog()
    captured_view = catalog.view() if has_structure else None
    normalized = normalize_md_job_spec(
        params=params,
        job_id=job_id,
        resolve_runtime_path=resolve_runtime_path,
        chemistry_catalog=catalog,
        chemistry_view=captured_view,
    )
    published_snapshots: list[Path] = []
    try:
        contract_dir = output_dir / "inputs"
        contract_dir.mkdir(parents=True, exist_ok=True)
        config_path = contract_dir / "md_job_config.json"
        input_config = dict(normalized["input"])
        expected_structure_sha256: str | None = None
        if input_config.get("structure"):
            profile = captured_view.get_profile(
                str(normalized["preparation"].get("chemistry_profile_id") or "")
            ) if captured_view is not None else None
            constraints = profile.get("launch_constraints") if isinstance(profile, Mapping) else None
            if not isinstance(constraints, Mapping):
                raise ChemistryProfileSelectionError(
                    "MD_CHEMISTRY_PROFILE_UNAVAILABLE",
                    "The selected molecular-dynamics chemistry profile is unavailable.",
                )
            expected_structure_sha256 = str(constraints["structure_sha256"])

        for field in ("structure", "coordinates", "topology"):
            source_value = input_config.get(field)
            if not source_value:
                continue
            snapshot, digest = _snapshot_input_file(
                source=Path(str(source_value)),
                field=field,
                contract_dir=contract_dir,
                expected_sha256=expected_structure_sha256 if field == "structure" else None,
            )
            published_snapshots.append(snapshot)
            input_config[field] = str(snapshot)
            input_config[f"{field}_sha256"] = digest
        normalized["input"] = input_config
        _validate_raw_md_job_spec(normalized)
        _atomic_write_contract(config_path, normalized)
    except Exception as exc:
        for snapshot in published_snapshots:
            try:
                snapshot.unlink(missing_ok=True)
            except OSError:
                pass
        if isinstance(exc, OSError):
            raise MDLaunchError(
                "MD_LAUNCH_SERVICE_UNAVAILABLE",
                "The molecular-dynamics launch could not be persisted.",
                status_code=503,
            ) from exc
        raise

    materialized = dict(params)
    materialized["md_job_spec"] = normalized
    materialized["md_job_config"] = str(config_path.resolve())
    return materialized
